eProsima/Fast-DDS-docs

- docs/pubsub.rst
Added an XML example in the section about how to disable multicast in Fast RTPS.
> Added xml example for disabling multicast.

- docs/geninfo.rst
- docs/genuse.rst
- docs/sources.rst
Fast-RTPS-Gen is not going to be directly available within Fast-RTPS and will need a separate build process.
> Refs #6341 Adapted documentation to the Fast-RTPS-Gen emancipation. [6353]

- code/CodeTester.cpp
TypeLookup PR changed the allowed constructors for `DynamicData_ptr` and `DynamicType_ptr`. This PR changes the examples to reflect that change.
> Fix examples. [6648]

- code/XMLTester.xml
PRs against 1.9.x are failing because the `log` tag on `XMLTester.xml` is inside the `<profiles>` tag, and it should be in the root of the xml.
> Fixing position of <log> tag

- code/CodeTester.cpp
- code/XMLTester.xml
- docs/realtime.rst
- docs/spelling_wordlist.txt
- docs/xmlprofiles.rst
Describes how to limit the size of variable length submessages: Partition, Userdata and Properties
DO NOT MERGE UNTIL THE CODE IS MERGED TOO
> Documentation of variable length submessage limits [7413]

- docs/advanced.rst
This PR expands the description of initial peers configuration, and adds a reference to it in the Simple Discovery Protocol
> Add initial peers in SDP

- README.md
- docs/conf.py
This PR completes the functionality that #138 was intended to add. 
Read the Docs documentation is generated directly with shpinx, meaning no use of `make` and therefore `CMake`. This meant that Fast DDS was not being downloaded, so the Doxygen documentation could not be generated. 
This PR fixes this issue by detecting when running on Read the Docs and acting accordingly. It also provides a small description on how to simulate the Read the Docs build environment locally.
> Download Fast DDS if running on Read the Docs [8473]

- docs/fastdds/logging/disable_module.rst
This PR removes EPROSIMA_INSTALLER_MINION documentation from the Logging section.
> Update CMake options in Logging section.

- docs/fastdds/library_overview/includes/architecture.rst
This comment was skipped when removing the references to SHM not being active by default
> Remove SHM as default on overview

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/transport/tcp/tls.rst
Add a comment explaining how the option and verify mode values can take compound values combining several enums. 
Also C++ and XML examples have been adapted to reflect this.
> how to combine verify modes and options in TLS

- code/DDSCodeTester.cpp
Creation of object is checked as `(obj != nullptr) //Error` when the correct form is `(obj == nullptr) //Error`
> Refs: #9194 fix error nullptr check

- code/CodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/rtps/history/IChangePool.rst
- docs/fastdds/api_reference/rtps/history/IPayloadPool.rst
- docs/fastdds/api_reference/rtps/history/history.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/spelling_wordlist.txt
Documenting the new PayloadPool on the RTPS layer:
- Add the IPayloadPool interface to the API-ref
- Add the IChangePool interface to the API-ref
- Describe the functionality of the pool
- Describe how the default implementation works
- Explain how to create endpoints with a custom pool
- Provide an example using a custom pool
**note**: Keeping it as draft as tests will fail until all implementations are in place in Fast DDS.
>  RTPS payload pool [9544]

- code/XMLTester.xml
- docs/fastdds/xml_configuration/common.rst
Fixes failing [nightly build](http://jenkins.eprosima.com:8080/job/nightly_fastdds-docs_master/499/), caused by an incorrect setting of the `PropertiesPolicyQoS` in the `XMLTester.xml` example code.
> Correct PropertiesPolicyType formatting [10117]

- docs/fastdds/logging/disable_module.rst
- docs/fastdds/logging/logging_configuration.rst
- docs/fastdds/logging/logging_messages.rst
- docs/installation/configuration/cmake_options.rst
Log refactor information added in Logging module.
CMake arguments separate in other subtitle *Log options*
> Log refactor docs update [10224]

- docs/fastdds/transport/shared_memory/shared_memory.rst
Added warning to prevent buffer ovewrite in a single message. Related to eProsima/Fast-DDS#1666. 
> Added a warning note for small segments sizes

- docs/requirements.txt
This PR fixes the style of TOC titles and unordered lists. It seems that it comes from a bug in `docutils` 0.17.0, which is a Sphinx dependency. Pinning `docutils` version to an older goes around the issue.
Related issues and PRs upstream:
* https://github.com/sphinx-doc/sphinx/issues/9051
* https://github.com/readthedocs/sphinx_rtd_theme/issues/1111
* https://github.com/sphinx-doc/sphinx/pull/9053
> Pin doc-utils version

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/publisher/dataWriter/dataWriter.rst
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/spelling_wordlist.txt
This PR documents the pull mode property section.
> [11113] Pull mode property documentation

- docs/03-exports/aliases-api.include
- docs/fastdds/statistics/dds_layer/domainParticipant.rst
- docs/fastdds/statistics/dds_layer/qos.rst
This PR also documents the `pushMode` property used in the `statistics::DataWriterQos`.
This PR depends on #251.
> [10991] Update Statistics QoS documentation

- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.h
- docs/fastdds/dds_layer/topic/fastddsgen/fastddsgen.rst
- docs/fastdds/getting_started/simple_app/includes/dataType.rst
- docs/fastddsgen/pubsub_app/includes/first_app.rst
- docs/fastddsgen/usage/usage.rst
- docs/installation/binaries/binaries_linux.rst
- docs/installation/binaries/binaries_windows.rst
- docs/notes/previous_versions/v1.10.0.rst
- docs/notes/previous_versions/v1.4.0.rst
- docs/notes/previous_versions/v1.5.0.rst
- docs/notes/previous_versions/v1.6.0.rst
- docs/notes/previous_versions/v1.7.0.rst
- docs/notes/previous_versions/v1.7.1.rst
- docs/notes/previous_versions/v1.7.2.rst
- docs/notes/previous_versions/v1.8.0.rst
- docs/notes/previous_versions/v1.8.1.rst
- docs/notes/previous_versions/v1.8.2.rst
- docs/notes/previous_versions/v1.8.3.rst
- docs/notes/previous_versions/v1.8.4.rst
- docs/notes/previous_versions/v1.9.0.rst
- docs/notes/previous_versions/v1.9.1.rst
- docs/notes/previous_versions/v1.9.2.rst
- docs/notes/previous_versions/v1.9.3.rst
- docs/notes/previous_versions/v1.9.4.rst
- docs/notes/previous_versions/v2.0.1.rst
- docs/notes/previous_versions/v2.0.2.rst
- docs/notes/previous_versions/v2.1.0.rst
- docs/spelling_wordlist.txt
This PR updates the name for `fastddsgen`. It also fixes a spelling error currently on master.
This PR depends on eProsima/Fast-DDS#1975 so the paths are correctly named.
> Update from `fastrtpsgen` to `fastddsgen`

- docs/installation/binaries/binaries_linux.rst
- docs/installation/binaries/binaries_windows.rst
Now CMake external projects can link either statically or dynamically to the **Fast-DDS** deployed binaries.
> [11498] Update docs to cover new installer feature

- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/dds_layer/core/entity/entity.rst
- docs/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.rst
- docs/fastdds/discovery/disc_callbacks.rst
This PR improves the documentation about `on_data_on_readers` and `on_data_available` callbacks.
It intends to solve #277.
> [12340] Improve documentation about callback conflicts

- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Since Fast DDS v2.4.0 in order to receive past samples in the DataReaders, besides setting the DurabilityQosPolicy, ReliabilityQosPolicy must be set to `RELIABLE`.
> [13276] DurabilityQosPolicy requires RELIABLE ReliabilityQosPolicy

- code/doxygen-config.in
This PR depends on eProsima/Fast-DDS#2395. It adds `DOXYGEN_SHOULD_SKIP_THIS` to doxyfile-config
> Add Doxygen skip definition to doxyfile

- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/transport/transport_api.rst
Discovery Server settings included the feature of specifying the locators address by name directly. This feature is not only for Discovery Server but for all locators. This PR moves the feature information to the locators section leaving a reference in the Discovery Server settings.
> Move DNS information from DS to Locators section [13611]

- docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
Fast DDS v2.5.0 introduced the dynamic network interfaces feature. However, in this version the feature is only officially supported in some specific cases that are clarified in this PR. This PR is related to eProsima/Fast-DDS#2468.
> [13780] Clarify scope and caveats of dynamic network interfaces

- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_windows.rst
Correct Windows installation from sources when using CMake
* Depends on eProsima/foonathan_memory_vendor#55
* Closes #338
> Correct CMake Windows installation from sources

- code/doxygen-config.in
With this PR, Doxygen ignores all the files in Fast DDS' installation `include/fastdds/thirdparty`
> Exclude thirdparty headers with Doxygen [13785]

- .github/workflows/mirror.yml
This PR adds a workflow to automatically backport contributions done to `master` into an array of release branches; namely `2.5.x` and `2.6.x`
> Add mirror workflow [13785]

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/rtps/builtin/data/ContentFilterProperty.rst
- docs/fastdds/api_reference/rtps/builtin/data/data.rst
- docs/fastdds/api_reference/rtps/rtps.rst
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/use_cases/realtime/allocations.rst
This PR adds documentation for the allocation limits introduced on eProsima/Fast-DDS#2552
> [13966] Documentation for content filter related allocation limits

- docs/installation/configuration/cmake_options.rst
Documentation follow up from https://github.com/eProsima/Fast-DDS/pull/2535
> Document CMake option APPEND_PROJECT_NAME_TO_INCLUDEDIR

- docs/fastddsgen/usage/usage.rst
This PR clarifies that:
* Fast DDS-Gen option `-typeobject` does not support generation of Python bindings when using at the same time option `-python` (eProsima/Fast-DDS-Gen#114)
* `-python` option is supported officially in more platforms than Windows currently.
> [14485] Hotfix: clarify `-python` Fast DDS-Gen option

- docs/docker/docker_demo/fast_dds_suite.rst
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/discovery/static.rst
- docs/fastdds/dynamic_types/examples.rst
- docs/fastdds/getting_started/simple_app/includes/sum_and_next_steps.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/fastdds/security/access_control_plugin/access_control_plugin.rst
- docs/fastdds/transport/shared_memory/shared_memory.rst
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/use_cases/well_known_deployments/well_known_deployments.rst
- docs/fastdds/use_cases/zero_copy/zero_copy.rst
This PR refers to #14543 and updates directories names of examples according to the parent task #14539.
This PR must be approved **only after** PR #2675 in Fast-DDS is approved to maintain consistency across Fast-DDS and Fast-DDS-docs repos.
> Refs #14543: Renamings in examples directories

- docs/fastdds/getting_started/simple_python_app/includes/subscriber.rst
The `HelloWorldSubscriber.py` was being downloaded as `HelloWorldPublisher.py`
> Correct Python example downloaded file name

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.5.0.rst
- docs/notes/previous_versions/v2.5.1.rst
- docs/notes/previous_versions/v2.5.2.rst
This PR adds the Fast DDS v2.5.2 release notes.
After being merged, please backport to `2.5.x`.
> [15161] Release v2.5.2

- docs/03-exports/aliases-api.include
- docs/fastdds/statistics/dds_layer/domainParticipant.rst
Further explanation on enabling statistics DataWriters and QoS editing.
Relates to FastDDS branch: [feature/XML_configuration_statistics_QoS](https://github.com/eProsima/Fast-DDS/tree/feature/XML_configuration_statistics_QoS)
Signed-off-by: Mikel Rico <mikelrico@eprosima.com>
> [15014] XML Configuration for statistics DataWriters QoS

- docs/docker/docker.rst
- docs/docker/fastdds/fast_dds.rst
- docs/docker/fastdds_suite/fast_dds_suite.rst
- docs/docker/includes/intro.rst
- docs/index.rst
1. Update name
1. Clarify difference between fastdds & fastdds-suite
1. Add section about fastdds image
> [15599] Docker Images section

- docs/conf.py
- docs/installation/configuration/cmake_options.rst
- docs/spelling_wordlist.txt
Documentation update associated with: https://github.com/eProsima/Fast-DDS/pull/2976
> Refs 15766: update shared_mutex docs

- docs/docker/includes/intro.rst
- docs/fastdds/use_cases/reduce_memory/reduce_memory.rst
This PR sets PREALLOCATED_WITH_REALLOC as the default memory policy. Also corrects a minor naming error when calling Ubuntu 22.04 Focal, which is 20.04.
This PR relates with eProsima/Fast-DDS#3102
Signed-off-by: Mario Dominguez <mariodominguez@eprosima.com>
> [16214] Set PREALLOCATED_WITH_REALLOC as default memory policy

- code/XMLTester.xml
- docs/fastdds/statistics/dds_layer/qos.rst
- docs/fastdds/statistics/dds_layer/troubleshooting.rst
eProsima/Fast-DDS#2998 changed the default Statistics DataWriter QoS but documentation was not updated accordingly.
> [16489] Fix default Statistics DataWriter QoS

- docs/fastdds/dds_layer/publisher/dataWriterListener/dataWriterListener.rst
- docs/fastdds/dds_layer/subscriber/dataReaderListener/dataReaderListener.rst
Since Fast DDS v2.1.0 `DataReaderListener::on_requested_deadline_missed` and `DataWriterListener::on_offered_deadline_missed` are implemented.
> [16795] Remove warning no longer applying

- docs/requirements.txt
By default, pip installs the lates version of jinja2 package (3.1) which issues an error in Readthedocs (readthedocs/readthedocs.org#9038).
This PR fixes the dependency version to avoid this issue and sorts the dependencies alphabetically.
> [16904] Fix jinja2 dependency to avoid build error

- CMakeLists.txt
- docs/fastdds/use_cases/request_reply/request_reply.rst
#436 introduced a regression because the tests are built without finding Sphinx package previously.
Spell check depends on this package to run.
This PR fixes this issue.
**REVIEWER**: even if the CI is green, the job output has to be checked to see if the spell check has been run.
> [17130] Fix spell check

- code/XMLTester.xml
- docs/fastdds/discovery/discovery_server.rst
- docs/fastddscli/cli/cli.rst
This PR adds documentation for using security on Discovery Server
> [15596] Secure discovery server

- docs/fastdds/security/access_control_plugin/access_control_plugin.rst
The property name was copy.pasted from previous section.
> Fix property name for access control plugin

- code/XMLTester.xml
- code/XMLTesterExample.xml
- docs/fastdds/xml_configuration/domainparticipant.rst
- Restore `<domainId>` tag in documentation
- Restore tag in ALL documentation XMLs
Rebased #455 
**This pull request should be merged right after #455 gets merged**
> [17206] Restore participant domainID tag in XML profile

- docs/index.rst
- docs/installation/sources/sources_qnx.rst
- docs/spelling_wordlist.txt
I added instructions for building Fast-DDS and running its tests and examples for QNX 7.1.
This PR is related to the [PR](https://github.com/eProsima/Fast-DDS/pull/3360) which adds support to QNX 7.1.
Any feedback is appreciated.
> Add instructions for building and running Fast-DDS on QNX 7.1

- code/DDSCodeTester.cpp
- code/XMLTester.xml
This PR corrects the whitelist snippets so that the actual whitelist in honored.
> Avoid using builtin transports on whitelist snippets

- docs/installation/binaries/binaries_linux.rst
- docs/installation/binaries/binaries_windows.rst
eProsima/Fast-DDS#3134 removed `FASTDDS_STATIC` CMake option and documentation was not updated correspondingly. This PR fixes it.
> [18449] Remove FASTDDS_STATIC CMake option

- docs/fastdds/transport/shared_memory/shared_memory.rst
This little PR adds a clarifying note regarding the potential problems of SHM and elevated users such as root. It is a follow-up to eProsima/Fast-DDS#3515
> [18627] Note on the usage of SHM with privileged users

- docs/fastdds/dds_layer/topic/contentFilteredTopic/createContentFilteredTopic.rst
This PR clarifies the constraints enforced in https://github.com/eProsima/Fast-DDS/pull/3565.
> [18763] Added Expression Parameter maximum values clarification

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/spelling_wordlist.txt
Adds documentation for eProsima/Fast-DDS#3753
@mergifyio backport 2.11.x 2.10.x 2.6.x
> [19263] User configuration for SHM metatraffic

- code/Examples/C++/DDSHelloWorld/src/HelloWorldPublisher.cpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldSubscriber.cpp
```c++
int samples = 10;
...
mysub->run(static_cast<uint32_t>(samples));
```
If the code just declares `samples` to be `uint32_t`, this static cast is not necessary, and the code is simpler.
> Remove unnecessary casts from C++ HelloWorld example

- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/discovery/general_disc_settings.rst
- docs/fastdds/discovery/simple.rst
- docs/fastdds/transport/shared_memory/shared_memory.rst
- docs/fastdds/use_cases/large_data/large_data.rst
- docs/fastdds/use_cases/well_known_deployments/well_known_deployments.rst
- docs/fastdds/use_cases/wifi/discovery_server_use_case.rst
Fix a few misspells in the Discovery Settings, Shared Memory Transport, and Typical Use Cases sections.
> Fix spelling mistakes in the docs

- code/XMLTesterSkipValidation.xml
- docs/fastdds/xml_configuration/making_xml_profiles.rst
This PR adds documentation for the feature introduced by https://github.com/eProsima/Fast-DDS/pull/3841
> [19583] Add documentation for environment variables expansion on XML

- docs/fastdds/dds_layer/publisher/dataWriter/dataWriter.rst
This fixes the `Mutable` column on the table describing `DataWriterQos`, that was found wrong during the development of eProsima/Fast-DDS#3915
> [19687] Fix documentation on immutable DataWriterQos

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/subscriber/dataReader/readingData.rst
- docs/fastdds/transport/datasharing.rst
- docs/fastdds/use_cases/zero_copy/zero_copy.rst
This PR corrects the code snippets where loans API was used to include the check for `is_sample_valid()`. It also adds references to the explanation, which, in turn, it has been emphasized.
If approved, we may need to backport to 2.11.x 2.10.x 2.6.x
> [19730] Add is_sample_valid() checks, references and emphasize

- code/DDSCodeTester.cpp
- code/Examples/C++/DDSHelloWorld/CMakeLists.txt
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPublisher.cpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldSubscriber.cpp
- code/XMLTester.xml
- code/XMLTesterExample.xml
- code/XMLTesterSkipValidation.xml
- docs/03-exports/aliases-api.include
- docs/03-exports/aliases.include
- docs/fastdds/api_reference/rtps/attributes/ThreadSettings.rst
- docs/fastdds/api_reference/rtps/attributes/attributes.rst
- docs/fastdds/api_reference/transport/transport_generic_interfaces.rst
- docs/fastdds/api_reference/transport/transport_generic_interfaces/port_based_transport_descriptor.rst
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/dds_layer/domain/domainParticipant/domainParticipant.rst
- docs/fastdds/dds_layer/domain/domainParticipantFactory/domainParticipantFactory.rst
- docs/fastdds/getting_started/simple_app/includes/publisher.rst
- docs/fastdds/getting_started/simple_app/includes/subscriber.rst
- docs/fastdds/library_overview/includes/exec_model.rst
- docs/fastdds/logging/logging_thread.rst
- docs/fastdds/transport/shared_memory/shared_memory.rst
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/transport/udp/udp.rst
- docs/fastdds/use_cases/large_data/large_data.rst
- docs/fastdds/xml_configuration/common.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
- docs/fastdds/xml_configuration/domainparticipantfactory.rst
- docs/fastdds/xml_configuration/log.rst
- docs/fastdds/xml_configuration/xml_configuration.rst
This PR adds documentation for the feature provided in [Fast DDS ThreadSettings](https://github.com/eProsima/Fast-DDS/tree/feature/thread-config/main).
Depends on:
* eProsima/Fast-DDS-python#69
> [19645] ThreadSettings documentation

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/xml_configuration/transports.rst
Add behavior of TCP transport when listening port is set to 0.
Documentation for PR: https://github.com/eProsima/Fast-DDS/pull/4061 (PR)
> Refs #20019: Add TCP listening port behavior when set to 0

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/transport/whitelist.rst
The feature gives users the possibility to add network interfaces to the whitelist by interface name as well, not just by their IP address.
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/3973
> [19780] Add interface whitelist by name

- docs/fastdds/env_vars/env_vars.rst
The feature allows the user to define a super client setting a new environment variable ROS_SUPER_CLIENT to true. This environment variable is used in combination with ROS_DISCOVERY_SERVER.
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/4047
> [19967] Define a super client by environment variable

- docs/installation/sources/sources_linux.rst
It is included below (twice), so it is removed from the wrong section
> Remove duplicated apt install dependency

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/env_vars/env_vars.rst
- docs/fastdds/use_cases/tcp/tcp_use_case.rst
- docs/fastdds/use_cases/tcp/tcp_with_discovery_server.rst
- docs/fastddscli/cli/cli.rst
This PR adds documentation for the new TCP features of Discovery Server CLI and the environment variable.
It also adds a case of use that uses TCP along Discovery Server
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/4097 (PR)
> [20021]  TCP support for Discovery server CLI and env var and example

- code/Examples/C++/DDSHelloWorld/src/HelloWorld.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorld.h
- code/Examples/C++/DDSHelloWorld/src/HelloWorldCdrAux.hpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldCdrAux.ipp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.h
This PR regenerate the example types. 
This is needed to introduce the (future) Fast DDS Gen release v3.2.1 changes in the (future) Fast DDS docs v2.13.1 release.
> [20176] Regenerate Fast DDS docs example types due to Gen release v3.2.1

- CMakeLists.txt
- code/Examples/C++/DDSHelloWorld/CMakeLists.txt
Reduce CMake minimum version required for Fast DDS compatibility against RHEL 9.
> [20176] Downgrade cmake version 

- docs/conf.py
The inclusion of `fastcdr/config.h` in Fast DDS Python's `fastdds.i` created a regression on the RTD generated documentation, as the Python API reference generation done with `SWIG` could not find that `fastcdr/config.h` file. This PR fixes that issue by creating the expected file (in opposition to cloning Fast CDR and configuring the real `config.h`.
> Fix Python API generation [20261]

- docs/fastddsgen/usage/usage.rst
- docs/spelling_wordlist.txt
This PR adds the documentation for the new `fastddsgen` option `flat-output-dir` https://github.com/eProsima/Fast-DDS-Gen/pull/287
> [20235] Fast DDS Gen flat-output-dir option usage

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/fastdds/transport/tcp/tcp.rst
Add non_blocking_send to TCPTransportDescriptor.
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/4237
> [20119] TCP socket send buffer limit

- docs/fastdds/rtps_layer/rtps_layer.rst
LARGE_DATA builtin transport no longer sets TCP `non_blocking_send` to true.
> Unset LARGE_DATA non-blocking-send parameter

- code/XMLTester.xml
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/troubleshooting/troubleshooting.rst
- docs/fastdds/use_cases/large_data/large_data.rst
- docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
This PR generally improves the documentation regarding the LARGE_DATA mode. 
- Adds a note recommending the manual configuration of the send and receive buffer sizes when using the LARGE_DATA mode. 
- Extends the current documentation regarding LARGE_DATA mode in the _Use Cases_ and the _TCP Transport_ sections to include the environment variable option. 
- Add a new bullet point to the _Troubleshooting_ section.
> [20501] Improve LARGE_DATA documentation

- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
This PR follows improves the History QoS configuration documentation and give some extra light regarding specific scenarios and compatibility with other QoS.
**Note**: This PR also updates the code / XML examples to the latest style followed in the documentation, as in continuous improvement.
Fast DDS related PR: 
- https://github.com/eProsima/Fast-DDS/pull/4375
Fixes https://github.com/eProsima/Fast-DDS/issues/4365
> [20401] Improve History QoS documentation and compatibility rules

- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
This PR adds documentation for:
* eProsima/Fast-DDS#4417
@Mergifyio backport 2.12.x 2.10.x 2.6.x
> [20503] Clarify history depth vs max_samples_per_instance inconsistency

- docs/notes/notes.rst
This PR fixes a typo in latest release notes v2.13.3 
@Mergifyio backport 2.13.x 2.12.x
> [20486] Fix typo in v2.13.3 release notes

- code/doxygen-config.in
This PR predefines `FASTDDS_TODO_BEFORE` to empty so it is substitute with nothing on the pre-processing step of Doxygen documentation generation, and thus Doxygen does not complain about it.
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x
- _N/A_: Documentation tests pass locally.
> [20527] Ignore FASTDDS_TODO_BEFORE macro on doxygen generation

- code/DDSCodeTester.cpp
Remove fastrtps fixed_size_string.hpp references. This PR is related with:
* eProsima/Fast-DDS#4269
- N/A Commit messages follow the project guidelines. 
> Remove fastrtps fixed_size_string.hpp references

- docs/fastdds/use_cases/tcp/tcp_use_case.rst
- docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
- docs/fastdds/use_cases/use_cases.rst
This PR improves explanation about LARGE_DATA and reorganizes the Typical Cases of Use.
> [20501] Improve large data docs

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/security.rst
- docs/fastdds/security/security.rst
This PR adds the documentation for configuring the `Authentication Handshake` behavior through the following properties:
* `max_handshake_requests`
* `initial_handshake_resend_period`
* `handshake_resend_period_gain` 
And also, fills the `PropertyPolicy Security` page by remembering the configurable properties of the different security plugins
We may backport this to 2.13.x 2.12.x 2.10.x and 2.6.x
> [20439] Authentication Handshake Properties documentation

- docs/fastdds/transport/tcp/tcp.rst
This related PR limits the amount of listening ports to one. If more listening ports are passed, those are ignored.
This PR documents this limitation.
* eProsima/Fast-DDS#4348
> [20313] Allow single listening port on TCP

- docs/03-exports/aliases-api.include
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/xml_configuration/transports.rst
With the related PR, the `tcp_negotiation_timeout` Transport Descriptor will be used to wait until logical port negotiation is finished prior sending data.
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x
* eProsima/Fast-DDS#4454
> [20508] TCP first message loss

- code/XMLTester.xml
This PR modifies the statistic data writer profile name of the xml file to troubleshoot statistics module, changing it to the right one. The error was pointed out in the issue https://github.com/eProsima/Fast-DDS/issues/4389.
@Mergifyio backport 2.13.x 2.12.x 2.10.x 
Fixes eProsima/Fast-DDS#4389
- N/A Commit messages follow the project guidelines. 
> [20551] Modify statistic data writer profile name in the xml file 

- docs/fastdds/use_cases/tcp/tcp_large_data_with_options.rst
This PR specifies how the sockets_size parameter in the builtin transports options affects the shared memory segment size. 
> [20501] Clarify how sockets_size affects SHM segment size

- docs/notes/previous_versions/previous_versions.rst
- docs/notes/previous_versions/v2.12.2.rst
This PR update 2.12.2 release notes
> [20029] Update 2.12.2 release notes

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.h
- docs/fastdds/api_reference/spelling_wordlist.txt
This PR migrates the following classes from include/fastrtps to fastdds:
-  IPLocator.h
-  md5.h
* eProsima/Fast-DDS#4518
- N/A Commit messages follow the project guidelines. 
> [20566] Migrate classes from include/fastrtps to fastdds

- docs/fastdds/api_reference/rtps/writer/LivelinessData.rst
- docs/fastdds/api_reference/rtps/writer/writer.rst
This PR removes `LivelinessData` from the API reference since it is made private in:
* eProsima/Fast-DDS#4545
> [20567] Remove LivelinessData from API reference

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/domain/domainParticipant/createDomainParticipant.rst
- docs/fastdds/xml_configuration/making_xml_profiles.rst
This PR includes documentation regarding new `DomainParticipantFactory` method that creates participants without arguments, taking relevant configuration from environment-loaded XML profiles (or default values).
* eProsima/Fast-DDS#4534
> [20543] Create Participant with default profile (use environment XML configuration)

- code/XMLTester.xml
- docs/fastdds/xml_configuration/dynamic_types.rst
This PR documents how to annotate members as key in XML types (`@key` equivalent)
@Mergifyio backport 2.13.x 2.10.x 2.6.x
* eProsima/Fast-DDS#4694
> [20733] Document how to annotate members as key in XML types

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
This PR adds reception threads configuration example to the docs.
@Mergifyio backport 2.13.x
> [20862] Add Reception threads configuration example

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/dds_pim/publisher/datawriterqos.rst
- docs/fastdds/api_reference/dds_pim/subscriber/datareaderqos.rst
- docs/fastdds/dds_layer/publisher/dataWriter/createDataWriter.rst
- docs/fastdds/dds_layer/subscriber/dataReader/createDataReader.rst
- docs/fastdds/python_api_reference/dds_pim/publisher/datawriterqos.rst
- docs/fastdds/python_api_reference/dds_pim/subscriber/datareaderqos.rst
- docs/spelling_wordlist.txt
This PR adds DATAREADER_QOS_USE_TOPIC_QOS and DATAWRITER_QOS_USE_TOPIC_QOS documentation and snippets on how to use them.
Related PR:
* eProsima/Fast-DDS/pull/4719
> [20861] Add DATAREADER_QOS_USE_TOPIC_QOS and DATAWRITER_QOS_USE_TOPIC_QOS

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.6.8.rst
- docs/notes/versions.rst
@Mergifyio backport 2.13.x 2.10.x
> [20825] Include v2.6.8 release notes

- docs/fastddsgen/python_bindings/python_bindings.rst
This PR adds a couple of notes improving python binding documentation regarding modules and namespaces
@Mergifyio backport 2.13.x 2.10.x 2.6.x 
Fixes eProsima/Fast-DDS-python#105
> [20551] Improve python bindings documentation

- docs/fastdds/api_reference/transport/transport_generic_interfaces/transport_interface.rst
Remove reference to `s_minimumSocketBuffer`, since it is being removed by eProsima/Fast-DDS#4760
- [__NO__] Commit messages follow the project guidelines. 
- I edited directly in github, and forgot to reference the redmine task. I put it in the PR title, though.
> [20976] Remove reference to removed constant

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/non_consolidated_qos.rst
This PR adds the documentation for max_message_size property in RTPS Writer and RTPS Participant.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x
* eProsima/Fast-DDS#4777
> [20849] New `max_message_size` property to limit output datagrams size

- code/Examples/C++/DDSHelloWorld/src/HelloWorldTypeObjectSupport.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldTypeObjectSupport.hpp
Regeneration of IDL source code to compile against eprosima/fast-dds#4746
- *N/A* Code snippets related to the added documentation have been provided.
> Automatic TypeObject representation registration for DynamicTypes [21056]

- code/CodeTester.cpp
This PR adds support for:
* eprosima/fast-dds#4546
> [20568] Adjust for removing all redundant headers from include/fastrtps

- docs/03-exports/aliases-api.include
- docs/fastdds/statistics/dds_layer/topic_names.rst
Remove RTPSMessageGroup from aliases-api includes.
Related PR in Fast DDS:
* https://github.com/eProsima/Fast-DDS/pull/4657
- N/A Documentation tests pass locally.
> [20709] Remove RTPSMessageGroup from aliases-api includes

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
In TransportConfigQos is missing the documentation of 
* Netmask filter ( introduced in https://github.com/eProsima/Fast-DDS/pull/4241 )
* max_msg_size_no_frag
@Mergifyio backport 2.14.x
> [21106] Add missing documentation of netmask filter and max_msg_size_no_frag in TransportConfigQos

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/use_cases/large_data/large_data.rst
This PR adds the XML configuration for FlowControllerDescriptor.
* eProsima/Fast-DDS#4837
- __NO__ Applicable backports have been included in the description.
> [21054] Add XML configuration for FlowControllerDescriptor

- docs/fastdds/logging/consumer.rst
- docs/installation/configuration/cmake_options.rst
This PR documents the change of making `StdoutErr` the default `LogConsumer`.
* eProsima/Fast-DDS#4873
- __NO__ Code snippets related to the added documentation have been provided.
- __NO__ Applicable backports have been included in the description.
> [21098] Change default logconsumer to StdoutErr

- docs/conf.py
This PR makes the RDT generation to fail if either of the `doxygen` or `swig` commands fails. Not checking them was causing the documentation to build with API reference errors.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x
* eProsima/Fast-DDS#4896
**NOTE**: As RTD build is not ready to take the appropriate Fast DDS branch and will choose `master`, the build will failed until eProsima/Fast-DDS#4896 is merged. I've verified on a Ubuntu 20.04 docker that the doxygen is generated without errors with that Fast DDS PR.
> [21114] Check suprocess return codes on RDT generation

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/use_cases/large_data/large_data.rst
This PR is a backport from #782 to `2.x`. It adds the XML documentation for flow controller descriptors.
@Mergifyio backport 2.13.x 2.10.x 2.6.x
> [21136] Add XML configuration for FlowControllerDescriptor to 2.x

- code/DDSCodeTester.cpp
#793 Introduced an ABI break changing `const char*` to `std:.string` in the flow controller descriptor name. This PR warns the user in the sample snippets that the name must be kept alive during participants lifetime.
**Important** This PR has to be cherry picked on the following backports:
* #802 
* #803 
* #804
- __NO__ (see PR description) Applicable backports have been included in the description.
> [21054] Make explicit the need to keep alive the flow controller descriptor name

- docs/fastdds/api_reference/rtps/common/CacheChange/ChangeForReaderCmp.rst
- docs/fastdds/api_reference/rtps/common/CacheChange/ChangeForReaderStatus_t.rst
- docs/fastdds/api_reference/rtps/common/CacheChange/ChangeForReader_t.rst
- docs/fastdds/api_reference/rtps/common/CacheChange/cachechange_toc.rst
This PR removes some public api reference regarding ChangeForReader* that is no longer available.
* eProsima/Fast-DDS#4923
- __NO__ Applicable backports have been included in the description.
> [21052] Remove public ChangeForReader* from api reference

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- docs/fastdds/rtps_layer/rtps_layer.rst
This PR updates the code examples that implement a CustomPayloadPool after the changes in `IPayloadPool` and derived classes. 
- It must be merged after: https://github.com/eProsima/Fast-DDS/pull/4892
> [21121] IPayloadPool refactor

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- code/XMLTesterExample.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
This PR updates the API of the Chaining Transports.
- Merge after: https://github.com/eProsima/Fast-DDS/pull/4537
> [20291] Gather-send implementation Docs

- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.h
- code/Examples/C++/DDSHelloWorld/src/HelloWorldTypeObjectSupport.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldTypeObjectSupport.hpp
- docs/fastdds/api_reference/spelling_wordlist.txt
This PR only regenerate the IDL files.
- eprosima/fast-dds#4874
- *N/A* Code snippets related to the added documentation have been provided.
> TypeObjectRegistry refactor [21135]

- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
- docs/installation/sources/sources_qnx.rst
- docs/installation/sources/sources_windows.rst
This PR is a copy of #811 for `2.x` that clarifies the `colcon build` command in the installation from sources sections avoiding the warning prompted while trying to build FastDDS Gen (non-CMake project dependency).
**Note**:  The link for versioning in the Gen section must not be backported.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
> [21155] 2.x - Improve build steps in the installation from sources sections

- code/DDSCodeTester.cpp
This PR adjust for the `include/fastrtps` removal from:
* eProsima/Fast-DDS#4930
It depends from the documentation changes from (docs PR not opened yet):
* eProsima/Fast-DDS#4898
- _N/A_; Applicable backports have been included in the description.
> [21159] Adjust for removal of include/fastrtps

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/dds_layer/core/policy/xtypesExtensions.rst
This PR updates the code examples of the QoS Policy to be more illustrative and include how the modified QoS should be used after editing it.
Additionally, it reviews that the API of QoS is identical for all entities that share a common QoS. It also makes the PropertyPolicyQoS of DataWriters and DataReader unmutable (such as the one of Participants), until a deeper study is made on what Policies should be mutable on enabled entities.
It also includes minor improvements in the readability of the docs (references, tabs, etc).
- It must be merged after: https://github.com/eProsima/Fast-DDS/pull/4842
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x
> [21077] Update Fast DDS docs QoS examples

- code/DDSCodeTester.cpp
- code/FastDDSGenCodeTester.cpp
- docs/fastdds/xtypes/language_binding.rst
> Enumerations are traslated to C++ signed integer enumerations [21215]

- docs/fastdds/api_reference/transport/shm_transport/test_shared_mem_transport_descriptor.rst
- docs/fastdds/api_reference/transport/shm_transport_interface.rst
As `test_SharedMemTransportDescriptor` is now public, we need to add it to the `api_reference`
* eProsima/Fast-DDS#4953
- __NO__ Applicable backports have been included in the description.
> [21131] Added test_shared_mem_transport_descriptor to api_reference

- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.0.rst
- docs/notes/previous_versions/v2.14.1.rst
- docs/notes/previous_versions/v2.14.2.rst
- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This PR adds the v2.14.2 release notes to Fast DDS Docs master
> [21209] Add v2.14.2 release notes

- code/CodeTester.cpp
This PR adapts the RTPS example code for the refactor in `WriterHistory`.
* eProsima/Fast-DDS#4966
> [21137] Adapt to RTPS WriterHistory refactor

- .github/workflows/config/build.meta
- .github/workflows/config/test.meta
- .github/workflows/config/test.repos
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/ubuntu-ci.yml
- RELEASE_SUPPORT.md
- docs/notes/versions.rst
This PR includes GitHub CI of this repo.
In this case, only Ubuntu workflow that builds Fast DDS docs, taking into account the Fast DDS and Fast DDS python branches.
**Note**: While backporting this PR, please ensure the following changes:
- Remove nightly jobs
- Update `ubuntu-ci.yml` file with the proper fallback branches
- Change `fastdds.repos` to `fastrtps.repos`
- 2.6.x requires building on `ubuntu-20.04`
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
> [21256] Migrate Fast DDS Docs CI to Github

- .github/workflows/reusable-ubuntu-ci.yml
In the previous PR 
- #831 
The Fast DDS and Fast DDS python related branches were not used as expected:
Instead of using the provided branch, it was downloading the .repos file from that branch (so the base reference was used instead of the desired branch).
This hotfix PR performs a checkout before downloading the repos included in the .repos file, so the actual branch used is the desired one.
In the case of the Fast DDS Python, its dependencies are already downloaded, so there is no need to download them. It has been changed to just cloning that repo and checking out to the desired branch.
**Important**: when fixing the conflicts in the backports, please ensure:
- Change `fastdds.repos` to `fastrtps.repos`
- change `src/fastdds` to `src/fastrtps`
@Mergifyio backport 2.14.x 2.13.x 2.10.x …
> [21256] Fix issue with Fast DDS and Fast DDS python deduced branches

- code/DDSCodeTester.cpp
This PR adjust the type of the method get_dynamic_type_builder_from_xml_by_name() to get DynamicTypeBuilder instead of DynamicType after the refactor of the corresponding implementation PR:
*  https://github.com/eProsima/Fast-DDS/pull/4970 
> [21184]  Adjust type in get_dynamic_type_builder_from_xml_by_name to return DynamicTypeBuilder

- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
- docs/installation/sources/sources_qnx.rst
- docs/installation/sources/sources_windows.rst
This PR clarifies the `colcon build` command in the installation from sources sections avoiding the warning prompted while trying to build FastDDS Gen (non-CMake project dependency).
Fixes eProsima/Fast-DDS/issues/4933
> [21155] Improve build steps in the installation from sources sections

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.13.5.rst
- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This PR includes the release notes of the recently release Fast DDS v2.13.5 in master
@Mergifyio backport 2.14.x 
> [21100] Include v2.13.5 release notes in master

- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
Nightly job was failing due to `os-image`-`os-version` name mismatched. 
This PR fixes it and moves `2.6.x` related jobs to weekly CI
- **N/A** Check contributor checklist is correct.
- **N/A** CI passes without warnings or errors.
> [21256] Fix nightly job and move 2.6.x to weekly CI

- docs/fastdds/api_reference/spelling_wordlist.txt
This PR fixes the error on spelling check due to eprosima/fast-dds#4985
- *N/A* Code snippets related to the added documentation have been provided.
> [21333] Fix spelling due to new class introduced in Fast DDS

- .github/workflows/reusable-ubuntu-ci.yml
- docs/conf.py
- readthedocs.yaml
#837 Moved both the CI and RTD generation to Ubuntu 24.04. Although it is a change we want to make, right now both Fast DDS and Fast DDS Python and having warnings and build errors on that platform which are uncovered by:
* #856
Until those are fixed, this PR sets the Ubuntu versions back to 22.04 for CI and 20.04.
- _N/A_: Documentation tests pass locally.
> [21309] Change back Ubuntu versions for CI and RTD

- docs/conf.py
This is caused because `pygment.css` is not included with new Sphinx version in the html. This PR fixes this.
@Mergifyio backport 2.14.x 2.13.x 2.10.x
> [21299] Fix code block not been colored after sphinx upgrade

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- code/XMLTesterExample.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/xml_configuration/datawriter.rst
This PR adapts the code to the RTPS writer APIs refactor. In particular, the rename of members in `WriterTimes`.
* eProsima/Fast-DDS#5028
> [21137] Account for changes on RTPS writer refactor

- docs/installation/binaries/binaries_linux.rst
- docs/installation/binaries/binaries_windows.rst
There were missing instructions regarding Fast DDS CLI in binary installation sections.
This PR adds that section in both Linux and Windows.
@Mergifyio backport 2.14.x 2.13.x 2.10.x
> [21319] Add python optional step in binary installation sections

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/dds_pim/xtypes/utils.rst
- docs/fastdds/xtypes/language_binding.rst
- docs/fastdds/xtypes/type_serializing.rst
This PR provides the documentation for the `idl_serialize` method.
https://github.com/eProsima/Fast-DDS/pull/4787
> [21051] Documentation to serialize DynamicTypes to IDL

- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.2.rst
- docs/notes/previous_versions/v2.14.3.rst
- docs/notes/versions.rst
This PR adds the Fast DDS v2.14.3 release notes to master. It is a forward port of:
* #867
> [21311] Add Fast DDS v2.14.3 release notes (#867)

- .github/workflows/ubuntu-ci.yml
This PR enables requesting CI on PRs that only modify `.txt` files, such as:
* #872
@Mergifyio backport 2.14.x 2.10.x 2.6.x
- _N/A_: Documentation tests pass locally.
> [21309] CI: `paths-ignore` only ignores modification in markdown files

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/xtypes/discovery_matching.rst
This PR is the Fast DDS Docs counterpart of
* eProsima/Fast-DDS#5081
> [21313] Type propagation policy

- README.md
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Some minor fixes in README and standarQosPolicies.rst
FIxed a minor error showing compatibility rules in standard Qos Policies
> Fix README and standardQosPolicies

- README.md
- code/Examples/C++/DDSHelloWorld/src/HelloWorldCdrAux.ipp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
- docs/02-formalia/titlepage.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.0.rst
- docs/notes/previous_versions/v2.14.1.rst
- docs/notes/previous_versions/v2.14.2.rst
- docs/notes/previous_versions/v2.14.3.rst
- docs/notes/previous_versions/v3.0.0.rst
- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This PR bumps the project version to 3.0.0 and adds the corresponding release notes.
-N/A Applicable backports have been included in the description.
> [21366] Bump version to v3.0.0

- docs/fastdds/discovery/simple.rst
This PR updates the inital peers documentation with the changes introduced in 
Note: spelling issue (unknown word `reachability`) is fixed in the [bump PR](https://github.com/eProsima/Fast-DDS-docs/pull/884/files#diff-94d41e6faf6c8f9c8faefc24c63640d92a798138e3eb709d528c4159e5b33d64)
Fixes eProsima/Fast-DDS/discussions/5153
> [21443] Fix bug in initial peers documentation

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/transport/listening_locators.rst
This PR improves the usage and definition of `mutation_tries` and gives extra information about the `participantId` usage too.
@Mergifyio backport 2.14.x 2.10.x 2.6.x 
Fixes eProsima/Fast-DDS#4754
> [21580] Improve `mutation_tries` documentation

- docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> [21590] Add warning about idls extensibility for Vulcanexus jazzy

- code/XMLTester.xml
- docs/fastdds/statistics/dds_layer/troubleshooting.rst
The XML snippet for statistics troubleshooting does not display the proper profile name for statistics writers.
This PR updates the snippet with the correct name and includes a warning box to inform about the profile name behavior.
@Mergifyio backport 2.14.x 2.10.x 2.6.x
> [21646] Fix typo in statistics troubleshooting XML snippet

- .github/workflows/mirror.yml
This PR mirrors the latest release `2.6.9` with `2.6.x` for addressing little documentation fixes.
*Note: Its possible that the job should be placed into master instead of 2.6.x to make any effect*
- **N/A** CI passes without warnings or errors.
> [21655] Mirror `2.6.9` with `2.6.x` ci job

- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/ubuntu-ci.yml
On previous PR the `swig4.1` dependency was introduced, which is only native available in `ubuntu-24.04` github runners.
This PR migrates all `master` workflows from `ubuntu-22.04` to `ubuntu-24.04`.
Depends on:
* #857
> [21578] Fix master build to run on Ubuntu 24.04

- code/XMLTester.xml
This PR adds the default subscriber profile in ROS 2 XML configuration snippet. This is particularly interesting for `2.6.x` as if the default profile defaults readers historymemroypolicy to PREALLOCATED. 
@Mergifyio backport 2.14.x 2.10.x 2.6.x
> [21655] Add default subscriber profile in ROS 2 XML configuration

- code/FastDDSGenCodeTester.cpp
- docs/fastdds/xml_configuration/dynamic_types.rst
- docs/fastdds/xtypes/language_binding.rst
- docs/fastddsgen/dataTypes/dataTypes.rst
This PR updates the documentation according with eprosima/fast-dds-gen#379 which adds support to `@value` annotation. 
> [21750] Add support @value annotation on fastddsgen

- docs/requirements.txt
After merging the FAQ section into the master branch, the readthedocs build fails at this step.
```
python -m sphinx -T -b readthedocssinglehtmllocalmedia -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/htmlzip
```
After research, it appears that the sphinx-toolbox 3.7.0 is not correctly read during build. Therefore, this PR updates the sphinx-toolbox version to 3.8.0.
https://github.com/sphinx-toolbox/sphinx-toolbox/pull/169
> [21416] Fix sphinx-toolbox version in requirements.txt

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.10.5.rst
- docs/notes/versions.rst
This adds the notes from release v2.10.5
@Mergifyio backport 2.14.x
> [21557] Add notes from v2.10.5

- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/persistence/persistence.rst
This PR documents the new behavior included in the implementation PR:
* Allows the creation of a DataWriter/Reader with a PERSISTENT durability, but behaving as TRANSIENT (warning about it).
* When in TRANSIENT, if no persistence guid is given, it fallbacks to TRANSIENT_LOCAL.
* eProsima/Fast-DDS#5224
> [21538] Allow all `durability` configurations

- code/CMakeLists.txt
> [21564] Update `fastdds_profiles.xsd` file location

- code/DDSCodeTester.cpp
- code/XMLTester.xml
This PR updates the XML snippets to meet the resource limits QoS constraints
@Mergifyio backport 3.0.x 2.14.x 2.10.x 2.6.x
> [21908] Adjust XML snippets to meet QoS constraints

- docs/fastdds/statistics/monitor_service/monitor_service_topics.rst
This PR brings the documentation for the `Extended Incompatible QoS` for monitor service.
* eProsima/Fast-DDS#5345
> [21841] Extended incompatible qos for monitor service documentation

- docs/fastdds/statistics/monitor_service/monitor_service_topics.rst
Documentation for the extended incompatible qos monitor service feature.
* eProsima/Fast-DDS#5385
> Extended incompatible qos for monitor service documentation (#945)

- .github/workflows/reusable-ubuntu-ci.yml
This adds a new step to the reusable workflow that lists the spell check errors produced during the test step.
See it in action [here](https://github.com/eProsima/Fast-DDS-docs/actions/runs/11836369838/job/32981112664)
> Add Spell Check error summary to reusable workflow

- docs/docker/fastdds_suite/fast_dds_suite.rst
As the benchmark example was not refactored with Fast DDS v3, we are removing it from the documentation until we add it. 
Fixes [#5398](https://github.com/eProsima/Fast-DDS/issues/5398)
> Remove benchmark example from docs

- docs/docker/fastdds/fast_dds.rst
As the benchmark example was not refactored with Fast DDS v3, we are removing it from the documentation until we add it.
* eProsima/Fast-DDS-docs#961
> Remove benchmark example from docker fastdds image docs

- code/FastDDSGenCodeTester.cpp
This PR adds a check fastcdr major version in FastDDSGenCodeTester source file. This should prevent that compilation against `fastcdr 1.0` from failing. 
> [21508] Check fastcdr major version in `FastDDSGenCodeTester` source file

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/library_overview/includes/functionalities.rst
- docs/fastdds/property_policies/security.rst
- docs/fastdds/security/auth_plugin/auth_plugin.rst
This adds documentation for the new property allowing the selection of the preferred key agreement algorithm.
@Mergifyio backport 3.1.x
We will backport to 3.1.x, but leaving the default value of the new property to the old behavior.
We will then backport from there into 3.0.x 2.14.x 2.10.x
* eProsima/Fast-DDS#5413
> [22280] Add documentation for `preferred_key_agreement` property

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/security.rst
- docs/fastdds/security/access_control_plugin/access_control_plugin.rst
- docs/fastdds/security/auth_plugin/auth_plugin.rst
This PR adds documentation for the new properties added in https://github.com/eProsima/Fast-DDS/pull/5450
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
> [22353] Document new `transmit_algorithms_as_legacy` on builtin security plugins

- docs/fastdds/security/includes/intro.rst
- docs/fastdds/transport/datasharing.rst
Add missing data-sharing with security incompatiblity warning, both in security and data sharing sections.
> Add data-sharing with security incompatiblity warning

- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
This PR regenerates the types with Fast DDS Gen `v4.0.3`
> [22497] Regenerate types with Fast DDS Gen 4.0.3

- docs/fastdds/dds_layer/core/status/status.rst
- docs/fastdds/dds_layer/domain/domainParticipant/createDomainParticipant.rst
- docs/fastdds/dds_layer/domain/domainParticipant/domainParticipant.rst
- docs/fastdds/dds_layer/publisher/dataWriter/createDataWriter.rst
- docs/fastdds/dds_layer/publisher/dataWriter/dataWriter.rst
- docs/fastdds/dds_layer/publisher/publisher/createPublisher.rst
- docs/fastdds/dds_layer/publisher/publisher/publisher.rst
- docs/fastdds/dds_layer/subscriber/dataReader/createDataReader.rst
- docs/fastdds/dds_layer/subscriber/dataReader/dataReader.rst
- docs/fastdds/dds_layer/subscriber/sampleInfo/sampleInfo.rst
- docs/fastdds/dds_layer/subscriber/subscriber/createSubscriber.rst
- docs/fastdds/dds_layer/subscriber/subscriber/subscriber.rst
- docs/fastdds/dds_layer/topic/topic/createTopic.rst
- docs/fastdds/dds_layer/topic/topic/topic.rst
- docs/fastdds/discovery/discovery_server.rst
Fixed some typos found while reading the documentation, fixed some links to c-InstanceHandle_Unknown and unified the format for the references to the different QOS_DEFAULT options.
> Fixed various typos and unified some formats in documentation

- docs/notes/migration_guide.rst
Modified the migration guide from Fast 2 to Fast 3. Eliminated some lines that referred to private files or internal tasks, and clarified a few points. Gave some change instructions a more clear "from ...  to ..." format. Almost completely deleted step 9 as for the users the examples' fate should matter little.
-  _N/A_ Code snippets related to the added documentation have been provided.
> [22012] Update migration guide removing things not related to application developer

- docs/fastddscli/cli/cli.rst
This PR updates CLI documentation regarding the `shm` command with the new option to delete data sharing segments.
* https://github.com/eProsima/Fast-DDS/pull/5549
> [21861] Enable Datasharing segments clean from CLI

- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/ubuntu-ci.yml
This PR is a port from eProsima/Fast-DDS#5220 to the `Fast DDS Docs` repository. It makes PR labeling based on workflow input.
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
> [22591] Allow run CI on external contributions

- .github/workflows/reusable-ubuntu-ci.yml
- docs/03-exports/aliases-api.include
- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/env_vars/env_vars.rst
- docs/fastdds/transport/listening_locators.rst
- docs/fastddscli/cli/cli.rst
- docs/notes/previous_versions/v2.6.0.rst
This PR updates documentation about the new Easy Mode feature.
Must merge after:
- https://github.com/eProsima/Fast-DDS/pull/5548
- https://github.com/eProsima/Fast-DDS/pull/5551#
> [22427] Fast DDS EASY_MODE - Feature - XMLRPC Server

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/troubleshooting/troubleshooting.rst
- docs/notes/migration_guide.rst
This PR warns about XTypes in the migration guide to Fast DDS v3.
* https://github.com/eProsima/Fast-DDS/pull/5601
> [22706] Warn about XTypes in Fast DDS v3

- docs/fastdds/ros2/ros2_configure.rst
This PR address this issue: https://github.com/ros2/rmw_fastrtps/issues/804
> Fix default ros2 publication mode

- docs/fastdds/env_vars/env_vars.rst
This PR adds an explanatory note to detail the behavior of the `service` XML profile loaded automatically by Fast DDS (if `ROS2_EASY_MODE` is enabled) and how it will behave in case the user has its own XML profile defined.
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/5617
> [22721] Increase 'max_blocking_time' in Easy Mode

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
- docs/fastddscli/cli/cli.rst
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/5689
> [22872] Configure ROS 2 Easy Mode via C++ and XML

- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
This PR adds a note about the hierarchy followed when configuring Easy Mode using multiple methods.
This PR depends on https://github.com/eProsima/Fast-DDS-docs/pull/1043 and must be merged after that one.
* https://github.com/eProsima/Fast-DDS/pull/5701
> [22873] Setup ROS 2 Easy Mode at participant creation

- docs/fastdds/xtypes/idl_parsing.rst
This PR updates the list of supported types in IDL Parser. Documentation PR for:
- https://github.com/eProsima/Fast-DDS/pull/5763
- __N/A__ Code snippets related to the added documentation have been provided.
- __N/A__ Applicable backports have been included in the description.
> [22972] Support sequences in IDL Parser

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.6.10.rst
- docs/notes/previous_versions/v2.6.9.rst
- docs/notes/previous_versions/v3.2.0.rst
- docs/notes/versions.rst
This PR forwards the notes from 2.6.10 to the supported versions
@Mergifyio backport 3.1.x 2.14.x 2.10.x
> [21559] Add notes from `2.6.10`

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/non_consolidated_qos.rst
This PR documents the new property added in:
- https://github.com/eProsima/Fast-DDS/pull/5795#
> [23078] Send only non-default QoS & Use 'serialize_optional_qos' for optional QoS in EDP messages

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/statistics/monitor_service/monitor_service_topics.rst
This PR adds the proper documentation for the related feature.
* eProsima/Fast-DDS#5818
> [23169] Documentation for the optional serialization of `WireProtocolConfigQos`

- docs/notes/previous_versions/v3.0.0.rst
- docs/notes/previous_versions/v3.0.1.rst
- docs/notes/previous_versions/v3.0.2.rst
- docs/notes/versions.rst
This PR adds a new table with the supported versions and also removes EOL version 3.0 from compatibilities
> [21427] Add Supported versions & Remove 3.0 from compatibilities

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/publisher/dataWriter/publishingData.rst
- docs/spelling_wordlist.txt
This PR adds the proper documentation of the corresponding feature in `Fast DDS`
* eProsima/Fast-DDS#5861
- NO Applicable backports have been included in the description.
> [23264] Add `DataWriter` sample prefilter documentation

- code/DDSCodeTester.cpp
- docs/fastddsgen/interfaces/exceptions.rst
- docs/fastddsgen/interfaces/interfaces.rst
- docs/fastddsgen/interfaces/introduction.rst
- docs/fastddsgen/rpc_calculator_basic_app/includes/code_generation.rst
- docs/fastddsgen/rpc_server_schedule/intro.rst
- docs/index.rst
This PR adds documentation for the feature introduced in https://github.com/eProsima/Fast-DDS-Gen/pull/482, and refactored in https://github.com/eProsima/Fast-DDS-Gen/pull/485
It also refactors the documentation on Fast DDS Gen for IDL interfaces, so that all topics are grouped under a single first-level title.
It is built on top of the following PR, and should be merged afterwards:
* https://github.com/eProsima/Fast-DDS-docs/pull/1088
> [23271] Add documentation for custom request scheduling

- docs/fastdds/xtypes/idl_parsing.rst
This PR adds the documentation related to:
- https://github.com/eProsima/Fast-DDS/pull/5890
> [22973] Support modules in IDL parser

- code/DDSCodeTester.cpp
This PR fixes a deprecation warning in `DDSCodeTester.cpp` caused by calling `SenderResource::send()` without specifying the transport priority.
> Fix deprecation warning in CustomChainingTransport

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/xtypes/idl_parsing.rst
Documentation for:
- https://github.com/eProsima/Fast-DDS/pull/5954
> [23508] Iterate over declared types processed with IDL Parser

- code/XMLTester.xml
- docs/fastdds/xml_configuration/transports.rst
This PR adds some missing fields to the transport descriptor documentation.
@Mergifyio backport 3.3.x 3.2.x 2.14.x
> [23592] Add missing fields to transport descriptor documentation

- .github/workflows/config/build.meta
Fast DDS Docs CI does not compile with warnings as errors enabled, so relevant warnings (e.g: deprecation warnings) are ignored. This PR fixes it.
@Mergifyio backport 3.3.x 3.2.x 2.14.x
Merge after:
- https://github.com/eProsima/Fast-DDS-docs/pull/1104
- _N/A: Documentation tests pass locally.
> Compile with warnings as errors in CI

- docs/fastdds/security/auth_plugin/auth_plugin.rst
- docs/fastdds/use_cases/large_data/large_data.rst
Adding root_CA extensions to the topic 8.1.1.1. and ensuring they’re applied.
Adding an option to change the min, default and max buffer size of sending and receiving sockets to the topic 15.4.1.1.1.
@Mergifyio backport 3.3.x 3.2.x 2.14.x
Fixes #23653
- [ N/A] Code snippets related to the added documentation have been provided.
> [23653] Documentation debt: TCP sockets and CA extensions configuration

- docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
- docs/fastdds/use_cases/ip_mobility/ip_mobility.rst
- docs/fastdds/use_cases/tsn/tsn.rst
- docs/fastdds/use_cases/use_cases.rst
> [23647] Add documentation for IP mobility

- .github/workflows/reusable-ubuntu-ci.yml
Since Fast DDS python requires CMake version 3.24, we need to update the CI here accordingly.
- _N/A_: The ``Pro`` version badge has been added if the documented feature is exclusive to Fast DDS Pro.
> [23747] Update CMake version in CI

- docs/fastdds/transport/low-bandwidth-transports.rst
- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v3.3.0.rst
- docs/notes/previous_versions/v3.4.0.rst
- _N/A_: The ``Pro`` version badge has been added if the documented feature is exclusive to Fast DDS Pro.
> [23520] Add release notes for v3.4.0
