- docs/advanced.rst
- docs/pubsub.rst
Added TCP to lists of transports available.
Added TCP configuration example.
Added custom transport definition and usage with XML.
Changed locator.set_IP4_address methods to the new IPLocator::setIPv4 methods.
> Added tcp transport user documentation.

- docs/advanced.rst
- docs/dynamictypes.rst
- docs/fastrtpsgen.rst
- docs/genuse.rst
- docs/index.rst
- docs/introduction.rst
- docs/pubsub.rst
- Added new page about dynamic types.
- Adapted some examples to show dynamic type variant.
- Added references yo dynamic types in related sentences.
> Dynamic types documentation added.

- docs/xmlprofiles.rst
[#4101](https://eprosima.easyredmine.com/issues/4101) Update the documentation of XML with an explanation of the new feature "XML environment variable"
> XML Environment Variable Docs [4101] 

- code/XMLTester.xml
- docs/xmlprofiles.rst
- Added explicit WAN section.
- Added new TCP descriptor configuration fields.
> TCP related updates [4388]

- code/CodeTester.cpp
- code/XMLTester.xml
- docs/pubsub.rst
- docs/xmlprofiles.rst
Adds documentation for lifespan
> Lifespan QoS documentation [5167]

- code/CodeTester.cpp
- code/XMLTester.xml
- docs/advanced.rst
- docs/pubsub.rst
- docs/xmlprofiles.rst
Adds documentation for deadline QoS
> Deadline QoS documentation [5154]

- code/CodeTester.cpp
- code/XMLTester.xml
- docs/pubsub.rst
- docs/spelling_wordlist.txt
- docs/xmlprofiles.rst
This PR adds documentation for disable positive acks QoS
> Disable positive acks documentation [5195]

- docs/notes.rst
- docs/xmlprofiles.rst
> Adds release notes for v1.8.1

- code/CMakeLists.txt
- code/CodeTester.cpp
- code/XMLTester.xml
- docs/advanced.rst
- docs/spelling_wordlist.txt
- docs/xmlprofiles.rst
- Updated source code examples
-Updated XML examples
- Compiled and run binary tester. Discovered a fast-RTPS static library installation issue.
- Update .rst explanations.
> Feature/discovery server [5908]

- docs/realtime.rst
Added documentation about how to enable strict real-time.
> STRICT_REALTIME documented. [6356]

- docs/notes.rst
> Release/1.9.1 [6434]

- code/XMLTester.xml
- docs/spelling_wordlist.txt
- docs/xmlprofiles.rst
> Xml avoid multicast 1.8.x

- code/XMLTester.xml
- docs/advanced.rst
- docs/xmlprofiles.rst
This PR adds documentation of #724.
> Update documentation with initial PDP [6457]

- Makefile
- code/CodeTester.cpp
- docs/dynamictypes.rst
This PR adds documentation about the TypeLookup Service.
> Feature/typelookup [6722]

- docs/notes.rst
Update Release notes for new release.
> Release notes for v1.9.4

- docs/persistence.rst
Warning about the usage of SQLite3 file by several processes.
> Added warning about SQLite3 [7761]

- code/XMLTester.xml
Several non-compliant duration values found in docs after merging eProsima/Fast-RTPS#1028
> Fixed empty duration values. [7832]

- .gitignore
- code/CodeTester.cpp
- code/XMLTester.xml
- docs/advanced.rst
- docs/fullxmloptions.xml
- docs/spelling_wordlist.txt
- docs/xmlprofiles.rst
Documentation of shared memory transport.
> Shared memory doc <master> [8054]

- code/XMLTester.xml
- docs/advanced.rst
- docs/fullxmloptions.xml
- docs/xmlprofiles.rst
SHM is now built-in transport.
OverflowPolicy parameters removed.
> SHM Transport documentation update <master> [8110]

- README.md
- code/CMakeLists.txt
- code/CodeTester.cpp
- code/doxygen-config.in
- docs/requirements.txt
- readthedocs.yaml
> Python dependencies

- docs/conf.py
> Update project name

- docs/fastdds/api_reference/dds_pim/dds_pim.rst
- docs/fastdds/dds_layer/dds_layer.rst
> Intro to DDS layer [8446]

- Makefile
- code/CMakeLists.txt
- code/CodeTester.cpp
> Fix nightly [8448]

- code/StaticTester.xml
- code/XMLTester.xml
> Fix most XML test errors

- code/StaticTester.xml
- code/XMLTester.xml
> Backport of #135: Fix almost all XML errors <master>

- code/CodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/transport/includes/intro.rst
- docs/fastdds/transport/includes/shm.rst
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
> No SHM transport by default [8493]

- code/DDSCodeTester.cpp
- docs/fastdds/dds_layer/core/entity/entity.rst
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/dds_layer/core/policy/xtypesExtensions.rst
- docs/fastdds/dds_layer/core/status/status.rst
- docs/fastdds/dds_layer/publisher/dataWriterListener/dataWriterListener.rst
- docs/fastdds/dds_layer/subscriber/dataReader/readingData.rst
- docs/fastdds/dds_layer/subscriber/dataReaderListener/dataReaderListener.rst
- docs/fastdds/dds_layer/subscriber/subscriberListener/subscriberListener.rst
- docs/fastdds/dds_layer/topic/topicListener/topicListener.rst
- docs/spelling_wordlist.txt
* Review Entities section
* Documentation of Status
* mini-ToCs on Policy
* Notes on not implemented listeners
* Reflect the need of looping to read available data
> DDS-status [8339]

- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/dds_layer/core/policy/policy.rst
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/dds_layer/core/policy/xtypesExtensions.rst
- docs/fastdds/dds_layer/dds_layer.rst
- docs/fastdds/dynamic_types/complex_types.rst
- docs/fastdds/dynamic_types/concepts.rst
- docs/fastdds/dynamic_types/dynamic_types.rst
- docs/fastdds/dynamic_types/supported_types.rst
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
> Limit ToC depth

- code/StaticTester.xml
> Correct Static XML [8597]

- docs/fastdds/env_vars/env_vars.rst
- docs/fastdds/library_overview/includes/functionalities.rst
Moved from overview to its own section.
> Environment variables [8581]

- CONTRIBUTING.md
- LICENSE
- README.md
- docs/02-formalia/titlepage.rst
> Contributing guidelines [8715]

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/core.rst
- docs/fastdds/dds_layer/core/policy/policy.rst
- docs/fastdds/dds_layer/core/status/status.rst
- docs/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.rst
- docs/fastdds/dds_layer/publisher/dataWriterListener/dataWriterListener.rst
- docs/fastdds/dds_layer/publisher/publisherListener/publisherListener.rst
- docs/fastdds/dds_layer/subscriber/dataReaderListener/dataReaderListener.rst
- docs/fastdds/dds_layer/subscriber/subscriberListener/subscriberListener.rst
- Remove warning 'not supported'
- Document the Status getters
- Some clarification on when the parent entity's listener is called
> Incompatible Qos [8811]

- docs/fastdds/xml_configuration/common.rst
> Correct default history depth in XML

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/persistence/persistence.rst
- docs/index.rst
- docs/spelling_wordlist.txt
Documentation of the persistence service feature added in eprosima/Fast-DDS#1291.
> Persistence service [8863]

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.0.0.rst
> Added Fast DDS v2.0.1 release notes [8944]

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fastdds/persistence/persistence.rst
- docs/fastdds/xml_configuration/common.rst
- docs/index.rst
- docs/installation/configuration/cmake_options.rst
- docs/spelling_wordlist.txt
Signed-off-by: imontesino <monte.igna@gmail.com>
> Added SQLITE3_SUPPORT description [8920]

- docs/conf.py
> Fixed common CSS style GET request timeout [9020]

- docs/conf.py
> Added return value to common css download exception.

- docs/fastdds/transport/whitelist.rst
> Updated whitelist definition.

- docs/fastdds/dds_layer/core/entity/entity.rst
> Refs: #8621 add warning listener

- docs/fastdds/discovery/includes/disc_mechanisms.rst
- docs/fastddscli/cli/cli.rst
> Refs #9280: Fix error discovery server CLI example

- docs/installation/configuration/cmake_options.rst
Updates cmake options according to eProsima/Fast-DDS#1375
> Add FORCE value to THIRDPARTY options

- docs/index.rst
- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
- docs/installation/sources/sources_windows.rst
- docs/spelling_wordlist.txt
…thers
Signed-off-by: imontesino <monte.igna@gmail.com>
> Added MacOS installation guide [9471]

- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
Signed-off-by: imontesino <monte.igna@gmail.com>
> Wrong default values in TransportConfigQos [9520]

- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
> Gradle installation note [9827]

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.0.2.rst
- docs/spelling_wordlist.txt
> v2.1.0 release notes

- code/CodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/rtps/history/IChangePool.rst
- docs/fastdds/api_reference/rtps/history/IPayloadPool.rst
- docs/fastdds/api_reference/rtps/history/history.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/spelling_wordlist.txt
* Refs 9544. Adding new interfaces to API-ref
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
* Refs 9544. alias for references to API-ref
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
* Refs 9544. Update RTPS doc with references to API-ref
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
* Refs 9544. Documentation of Payload pool
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
* Refs 9544. Example with custom Payload pool
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
* Refs 9544. Suggestions and documentation check errors
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
>  RTPS payload pool

- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
> Gradle installation note <2.0.x> [9882]

- code/DDSCodeTester.cpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldSubscriber.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> Changed deprecated ALIVE by ALIVE_INSTANCE_STATE in code tester [10184]

- docs/02-formalia/titlepage.rst
- docs/fastdds/discovery/discovery_server.rst
This is a re-work of #215 . Kudos to @DaveJarvis for the original catch and PR!
> Use inclusive language

- docs/fastdds/ros2/discovery_server/discovery_packets.py
- docs/fastdds/ros2/discovery_server/no_intraprocess_configuration.xml
- docs/fastdds/ros2/discovery_server/ros2_discovery_server.rst
XML configuration added to intra-process.
Scripts refactor.
> Fix last script in Discovery Server [10009]

- docs/fastdds/api_reference/spelling_wordlist.txt
> Add infos to dict [10319]

- docs/fastdds/api_reference/dds_pim/core/core.rst
- docs/fastdds/api_reference/dds_pim/core/loanablearray.rst
- docs/fastdds/api_reference/dds_pim/core/loanablecollection.rst
- docs/fastdds/api_reference/dds_pim/core/loanablesequence.rst
- docs/fastdds/api_reference/dds_pim/core/stackallocatedsequence.rst
- docs/fastdds/api_reference/spelling_wordlist.txt
Added API reference for the following classes and structs:
* `LoanableArray`
* `LoanableCollection`
* `LoanableSequence`
* `StackAllocatedSequence`
> Add loanable sequences API reference [10335]

- docs/installation/sources/sources_windows.rst
Ensure powershell commands work as they are written.
> Fixed installation commands on windows [10396]

- code/XMLTester.xml
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/ros2/ros2_configure.rst
- docs/spelling_wordlist.txt
Complete the ROS2 configuration section.
> Update Ros2 configuration [10478]

- docs/installation/binaries/binaries_windows.rst
Described dependencies for Windows binaries installation are not necessary. This PR removes them.
> Windows installation: remove dependencies [10490]

- docs/03-exports/aliases-api.include
- docs/fastdds/env_vars/env_vars.rst
- docs/fastddscli/cli/cli.rst
> Add remote servers to server using env variable [10613]

- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/logging/disable_module.rst
- docs/fastdds/logging/logging_configuration.rst
- docs/installation/configuration/cmake_options.rst
Docs update according with [[10637] #1775](https://github.com/eProsima/Fast-DDS/pull/1775)
> [10670] Adding the FASTDDS_ENFORCE_LOG_INFO option

- docs/fastdds/dds_layer/domain/domainParticipant/createDomainParticipant.rst
> Add warning to domainId maximum

- docs/fastdds/use_cases/reduce_memory/reduce_memory.rst
> Correct typo on reduce memory tutorial

- docs/03-exports/aliases-api.include
- docs/requirements.txt
> Updated breathe python module and fixed namespaces

- docs/fastdds/api_reference/spelling_wordlist.txt
> Hotfix: add to spelling wordlist DataWriterQos and DataReaderQos

- docs/fastdds/statistics/dds_layer/qos.rst
> [10718] Remove pull mode QoS

- docs/fastdds/statistics/includes/intro.rst
> Fix reference

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/discovery/static.rst
Depends on eProsima/Fast-DDS#1818
> Update to new api to set static edp xml content [11002]

- docs/fastdds/transport/shared_memory/shared_memory.rst
> [11135] Hotfix: clarify how to open dump file with Wireshark

- docs/fastdds/api_reference/api_reference.rst
> Add Link to doxygen API ref

- docs/fastddsgen/usage/usage.rst
- docs/spelling_wordlist.txt
> Document -typeros2 option

- docs/fastdds/statistics/dds_layer/domainParticipant.rst
- docs/fastdds/statistics/dds_layer/statistics_dds_layer.rst
- docs/fastdds/statistics/dds_layer/topic_names.rst
- docs/fastdds/statistics/includes/intro.rst
> Remove statistic module unimplemented warnings on docs

- docs/02-formalia/titlepage.rst
- docs/fastdds/ros2/discovery_server/ros2_discovery_server.rst
- docs/fastdds/ros2/ros2.rst
- docs/fastdds/ros2/ros2_configure.rst
- docs/fastdds/use_cases/use_cases.rst
This PR updates the documentation to ROS 2 Galactic.
The spelling error is fixed in #266.
> [11596] Update to ROS 2 Galactic

- docs/fastdds/logging/disable_module.rst
- docs/installation/configuration/cmake_options.rst
Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>
> Clarify behaviour of logInfo depending on defines and cmake options [12287]

- docs/fastdds/dds_layer/core/status/status.rst
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Remove unsupported warning on deadline statuses

- code/DDSCodeTester.cpp
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/discovery/discovery_server.rst
- docs/spelling_wordlist.txt
This PR provides documentation for:
* eProsima/Fast-DDS#2142
Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>
> Add remote servers on run-time [12278]

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/env_vars/env_vars.rst
- docs/fastddscli/cli/cli.rst
This PR provides documentation for:
* eProsima/Fast-DDS#2140
> Configuration of Discovery Server using names instead of addresses [12349]

- docs/03-exports/aliases-api.include
- docs/fastdds/api_reference/rtps/flowcontrol/FlowControllerDescriptor.rst
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
- docs/fastdds/statistics/dds_layer/qos.rst
This PR includes the required documentation changes for eProsima/Fast-DDS#2176 and eProsima/Fast-DDS#2180
Depends on #284
> Changes on recomended statistics DataWriterQoS [12520]

- code/environment_file_format.json
- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/env_vars/env_vars.rst
> [12199] FASTDDS_ENVIRONMENT_FILE environment variable

- docs/notes/notes.rst
> Update v2.4.1 release notes

- docs/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.rst
- docs/fastdds/dds_layer/subscriber/dataReaderListener/dataReaderListener.rst
- docs/fastdds/dds_layer/subscriber/subscriberListener/subscriberListener.rst
> Add listener hierarchy notice to DataReader and Subscriber listeners

- code/DDSCodeTester.cpp
- colcon.pkg
- docs/conf.py
- docs/fastdds/transport/transport_api.rst
- docs/requirements.txt
This PR documents eProsima/Fast-DDS#2103.
> Document chaining transports [13115]

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
- docs/fastdds/use_cases/use_cases.rst
Related to eProsima/Fast-DDS#2310
> [12987] Add dynamic network interfaces documentation

- README.md
#300 Sets a dependency from `sphinxcontrib.plantuml`
#311 installs `plantuml` in the RTD docker container
This PR updates the README.md with instructions to install `plantuml`
> Add instructions to install plantuml [13300]

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/xml_configuration/making_xml_profiles.rst
- docs/fastdds/xml_configuration/xml_configuration.rst
Documentation eProsima/Fast-DDS#2245
> [12821] Load XML from string data buffer

- docs/installation/sources/sources_windows.rst
Fixing local windows installation from sources steps
> Refs 13262. Fixing

- docs/fastddsgen/introduction/introduction.rst
- docs/fastddsgen/pubsub_app/includes/workspace.rst
- docs/fastddsgen/python_bindings/python_bindings.rst
- docs/fastddsgen/usage/usage.rst
- docs/index.rst
- docs/installation/sources/sources_linux.rst
> [13318] Add python bindings section to Fast DDS-Gen documentation

- docs/fastddsgen/dataTypes/dataTypes.rst
> [13387] IDL maps support clarification

- docs/fastdds/dds_layer/topic/instances.rst
> [13804] Hotfix: Add examples titles

- docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
- docs/fastdds/use_cases/use_cases.rst
- docs/spelling_wordlist.txt
Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>
> [13805] Use Case - Record Replay with Rosbag 

- code/DDSCodeTester.cpp
- docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
- docs/fastdds/use_cases/use_cases.rst
- docs/spelling_wordlist.txt
Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>
> [13805] Record Replay use case documentation improvement

- CMakeLists.txt
- docs/conf.py
This PR allow to generate the documentation without having the python bindings.
> Fix compilation without python bindings [13901]

- docs/installation/sources/sources_linux.rst
Include an explanation of the softhsm2 group on linux
> [13829 ] add non-root users to the softhsm2 group

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/topic/instances.rst
- docs/spelling_wordlist.txt
> [13804] Improve instances examples

- code/StaticTester.xml
- docs/fastdds/discovery/static.rst
Depends on eProsima/Fast-RTPS#2355
> Add disablePositiveAcks documentation to Static Discovery section [13286]

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/conf.py
- docs/fastdds/discovery/includes/disc_phases.rst
- docs/fastdds/property_policies/non_consolidated_qos.rst
- docs/fastdds/statistics/dds_layer/qos.rst
- docs/fastdds/statistics/dds_layer/topic_names.rst
- docs/requirements.txt
This PR documents eProsima/Fast-DDS#2549
> Extend DISCOVERY_TOPIC to include physical information [14006]

- docs/fastdds/discovery/discovery_server.rst
This PR documents new feature eProsima/Fast-DDS#2555
> [13944] Possibility of modifying remote server locators

- docs/conf.py
- docs/fastdds/property_policies/non_consolidated_qos.rst
This PR fixes the tabs style introduced in #352
> Fix tabs CSS

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
- docs/fullxmloptions.xml
Depends on:
* eProsima/Fast-DDS#2554
> Add doc about GroupData, TopicData.. on XML [14087]

- docs/fastdds/use_cases/large_data/large_data.rst
- docs/spelling_wordlist.txt
Added information about txqueuelen modification.
> Update large_data.rst [14088]

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/discovery/static.rst
- docs/fastdds/property_policies/non_consolidated_qos.rst
Depends on:
* eProsima/Fast-DDS#2350
> Document new static discovery property to select exchange format [14095]

- docs/02-formalia/titlepage.rst
- docs/fastdds/ros2/discovery_server/ros2_discovery_server.rst
- docs/fastdds/ros2/ros2.rst
- docs/fastdds/use_cases/use_cases.rst
- docs/fastddsgen/python_bindings/python_bindings.rst
- docs/spelling_wordlist.txt
* Fast DDS-Gen v2.1.2 supports Python bindings in Windows.
* Update ROS 2 information about latest release.
> [14124] Update ROS 2 information and remove obsolete note

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.5.1.rst
- docs/spelling_wordlist.txt
> [14124] Fast DDS v2.6.0 release notes

- docs/04-common/python_requirements.rst
Related to eProsima/Fast-DDS-python#30
> [14804] SWIG dependency requirement

- docs/installation/sources/sources_linux.rst
Signed-off-by: Victor Maroto <victormaroto@eprosima.com>
> Clarify Linux installation from sources [13767]

- docs/fastdds/dds_layer/core/status/status.rst
- docs/fastdds/dds_layer/subscriber/dataReaderListener/dataReaderListener.rst
Merge after:
- eProsima/Fast-DDS#2708
> Add documentation new feature: SampleRejectedStatus [14826]

- docs/03-exports/aliases-api.include
- docs/fastdds/transport/tcp/tls.rst
This PR:
* Adds documentation for eProsima/Fast-DDS#2763
* Marks the feature as *Unimplemented*
> [15013] Add SNI configuration to TLSConfig

- docs/fastdds/transport/shared_memory/shared_memory.rst
> [14935] Clarify SHM usage when other transports are enabled

- .github/workflows/mirror.yml
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Change mirror workflow to 2.7.x

- docs/installation/configuration/cmake_options.rst
- docs/spelling_wordlist.txt
Associated with  https://github.com/eProsima/Fast-DDS/pull/2846/commits
> [15174] Include new USE_THIRDPARTY_SHARED_MUTEX CMake options

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.1.2.rst
> [15163] Fast DDS v2.1.2 release notes

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.3.5.rst
> [15160] Add release notes Fast DDS v2.3.5

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.6.2.rst
- docs/spelling_wordlist.txt
> [15162] Add Fast DDS v2.6.2 release notes

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.6.1.rst
- docs/spelling_wordlist.txt
> [15162] Add Fast DDS 2.6.2 release notes <2.6.x>

- code/CMakeLists.txt
- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/discovery/static.rst
Change check static xml discovery test from rtps tests to dds tests
* This PR is dependent on eProsima/Fast-DDS#2817
Signed-off-by: Inés Luño <inesluno@eprosima.com>
> [13824]Change check static xml discovery test from rtps tests to dds tests

- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/core/waitsets/waitsets.rst
- docs/fastdds/discovery/static.rst
- docs/notes/notes.rst
- docs/notes/previous_versions/v2.7.0.rst
> [15159] Fast DDS v2.7.1 release notes

- .github/workflows/mirror.yml
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Add 2.8.x to mirror workflow.

- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/subscriber/dataReader/readingData.rst
> Add subsections to accessing data section

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
> Document new PropertyQoS propagate

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/transport/tcp/tls.rst
- docs/fastdds/xml_configuration/transports.rst
> Add SNI documentation

- docs/03-exports/aliases.include
> [15600] Fix references in statistics section

- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/persistence/persistence.rst
This PR:
* Fixes the incomplete snippet
* Includes the C++ and XML snippets into tabs
> [16123] Fix incomplete XML snippet on persistence service

- docs/installation/configuration/cmake_options.rst
> Add SANITIZER cmake option documentation

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.3.0.rst
- docs/notes/previous_versions/v2.3.1.rst
- docs/notes/previous_versions/v2.3.2.rst
- docs/notes/previous_versions/v2.3.3.rst
- docs/notes/previous_versions/v2.3.4.rst
- docs/notes/previous_versions/v2.3.5.rst
- docs/notes/previous_versions/v2.3.6.rst
> [16171] Fast DDS v2.3.6 release notes

- .github/workflows/mirror.yml
> [16076] Mirror master on to both 2.8.x & 2.9.x

- code/XMLTester.xml
- docs/03-exports/aliases-api.include
- docs/fastdds/xml_configuration/common.rst
- docs/fastdds/xml_configuration/datareader.rst
- docs/fastdds/xml_configuration/datawriter.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
This PR fixes several issues in the XML section:
* Add Data Sharing XML configuration.
* Fix some labels.
* Fix some cross references.
* Fix some table of contents missing some subsections.
* Update some tables to `list-tables`.
> [16290] Hotfix: fix several XML properties

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.6.3.rst
> [16332] Fast DDS v2.6.3 release notes

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.6.4.rst
> [16801] Fast DDS v2.6.4 release notes

- .github/workflows/mirror.yml
This PR adds a mirror from master to 2.10.x
> [16802] Add mirror to 2.10.x

- CMakeLists.txt
- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/use_cases/request_reply/request_reply.rst
- docs/fastdds/use_cases/use_cases.rst
This PR adds a new use case: Request-Replyg communication.
Depends on:
- eProsima/Fast-DDS#3173
> Add request-reply use case [16609]

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.1.3.rst
> [16904] Fast DDS v2.1.3 release notes

- docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Depends on:
- eprosima/fast-dds#3228
> Add missing information in ResourceLimitsQosPolicy [16819]

- docs/fastdds/xml_configuration/common.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
- docs/fastdds/xml_configuration/dynamic_types.rst
Signed-off-by: JesusPoderoso <jesuspoderoso@eprosima.com>
> [17046] Add angle brackets to missing elements in locators XML profile

- .github/workflows/mirror.yml
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Remove 2.9.x from mirror

- docs/fastdds/xml_configuration/transports.rst
Tests passed locally
Signed-off-by: JesusPoderoso <jesuspoderoso@eprosima.com>
> [17153] Set TLS verify paths as list of strings (transport descriptors)

- docs/requirements.txt
This PR supersedes #450 and #438.
Documentation has been generated locally and the following features checked that were correctly generated:
* Bullet lists
* API reference
* Tabs
* Snippets
* References
Upgrade does not seem to break anything.
> [17519] Upgrade dependencies fixing a couple of security vulnerabilities

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.rst
Implementation PR: https://github.com/eProsima/Fast-DDS/pull/3412
> [17873] Added ignore_participant documentation

- code/DDSCodeTester.cpp
- code/XMLTester.xml
- docs/fastdds/discovery/general_disc_settings.rst
- docs/fastdds/property_policies/ignore_local_endpoints.rst
- docs/fastdds/property_policies/property_policies.rst
- docs/spelling_wordlist.txt
This PR adds the documentation for the Ignore local endpoints documentation at the `DomainParticipant` level.
> [18153] DomainParticipant ignore_local_endpoints documentation

- docs/notes/notes.rst
- docs/notes/previous_versions/v2.8.0.rst
- docs/notes/previous_versions/v2.8.1.rst
- docs/notes/previous_versions/v2.8.2.rst
- docs/spelling_wordlist.txt
Adding 2.8.2 notes and marking 2.8.x releases as EOL.
> [17831] Added 2.8.2 notes and marked old 2.8.x releases as EOL

- code/XMLTester.xml
- code/XMLTesterExample.xml
- docs/fastdds/dynamic_types/discovery.rst
- docs/fastdds/xml_configuration/domainparticipant.rst
Related to eProsima/Fast-DDS#3547
> [18728] Support typelookupservice settings in XML

- docs/fastdds/use_cases/large_data/large_data.rst
> [18907] Fix Large data use cases Reliability kind typo

- README.md
This PR makes several small corrections to the Fast DDS-Docs installation guide
> [18154] Fast DDS-Docs installation guide corrections

- docs/fastddsgen/usage/usage.rst
- docs/spelling_wordlist.txt
Pull Request https://github.com/eProsima/Fast-DDS-Gen/pull/84 is adding a new option to Fast DDS-Gen so the user is able to provide custom templates to use. 
This PR adds this option to the Usage section.
> [13762] Added custom template option to Fast DDS-Gen

- docs/installation/binaries/binaries_windows.rst
Depends on:
- eProsima/Fast-DDS#3134
> New loading of cmake targets [16591]

- docs/fastdds/discovery/discovery_server.rst
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/2924
> Include reference to DiscoveryServerExample [12368]

- docs/conf.py
- docs/docker/docker.rst
- docs/docker/shm_docker.rst
This PR adds a section to document how to leverage SHM and Data-sharing in Docker deployments
> [19032] Document use of Docker and SHM/Data-sharing

- docs/fastdds/library_overview/includes/exec_model.rst
- docs/fastdds/library_overview/library_overview.rst
- docs/spelling_wordlist.txt
Partial rewriting of threading information to include additional information and all threads spawned by Fast DDS, as well as their cardinality and conditions.
> [18965] Improved threading model information

- docs/fastdds/transport/listening_locators.rst
This PR closes #520.
@Mergifyio please backport 2.10.x 2.9.x 2.6.x
> [19089] Fix typo

- docs/fastdds/library_overview/includes/exec_model.rst
DataSharing listener changed to One per DataReader
Security Logging thread changed to one per DomainParticipant
> [19191] Fixed Threading model table

- docs/fastddsgen/usage/usage.rst
Custom templates were introduced in Fast DDS-Gen v2.5.0 (attached to Fast DDS v2.11.x).
> [19478] Clarify custom template usage

- docs/fastdds/api_reference/spelling_wordlist.txt
- docs/fastdds/transport/transport_api.rst
- docs/spelling_wordlist.txt
Fixes [#3857](https://github.com/eProsima/Fast-DDS/discussions/3857)
> [19570] Improve locators documentation

- docs/fastddsgen/dataTypes/dataTypes.rst
This PR adds the IDL modules documentation. It closes #406.
> [19638] Add IDL modules

- code/XMLTester.xml
- docs/fastdds/discovery/discovery_server.rst
- docs/fastddscli/cli/cli.rst
* Refs #15596. Added XML profile for CLI example.
* Refs #15596. CLI examples updated.
* Refs #15596. Added note regarding security configuration.
* Refs #15596. Introduction on discovery server section.
* Refs #15596: Add security section to discovery server
---------
> [20026] Secure discovery server (backport #437)

- docs/notes/previous_versions/v2.11.3.rst
This PR fixes an error introduced in 
- #673 
That set the v2.11.3 release notes with a higher title hierarchy that the required.
> [20486]  Fix release notes title

- docs/installation/configuration/cmake_options.rst
This PR adds documentation for the CMake option `FASTDDS_EXAMPLE_TESTS` introduced on:
* eProsima/Fast-DDS#4466
> [19175] Documentation of FASTDDS_EXAMPLE_TESTS CMake option

- docs/fastdds/use_cases/tcp/tcp_use_case.rst
- docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
- docs/fastdds/use_cases/use_cases.rst
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x 
- [N/A] Code snippets related to the added documentation have been provided.
> [20501] Rearrange use cases list

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
This PR removes all the XML parser APIs that have been made private in this PR:
* eProsima/Fast-DDS#4318
> Remove private XML parser APIs

- code/Examples/C++/DDSHelloWorld/src/HelloWorldv1.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldv1.h
This PR updates the documentation types according to the latest Fast DDS Gen released v3.3.0 version.
> [20495] Regenerate docs types: Fast DDS Gen v3.3.0

- CMakeLists.txt
- code/Examples/C++/DDSHelloWorld/CMakeLists.txt
Downgrade cmake version to 3.20 in code/Examples/c++/DDSHelloWorld/CMakeList.txt and upgrade 3.12 in CMakeList.txt
Reference PR in docs master: 
* eProsima/Fast-DDS-docs/pull/635
Related fastdds PR:
* eProsima/Fast-DDS#4232
- N/A Documentation tests pass locally.
> Downgrade cmake version to 3.20

- docs/notes/versions.rst
This PR adds 2.14.x to the list of supported versions.
* eProsima/Fast-DDS#4579
> [20644] Add 2.14.x to versions.rst

- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.0.rst
- docs/spelling_wordlist.txt
This PR adds the release notes for Fast DDS v2.14.0
> [20645] Add Fast DDS v2.14.0 release notes

- docs/notes/previous_versions/v2.13.3.rst
This PR removes a leftover `latest` mark on 2.13.3 release notes.
> [20644] Remove latest mark from 2.13.3

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.13.4.rst
- docs/notes/versions.rst
This PR includes the release notes of Fast DDS v2.13.4 in latest documentation (master)
> [20723] Include v2.13.4 release notes

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- README.md
- docs/02-formalia/titlepage.rst
This PR prepares the 3.0.x-devel branch to become Fast DDS Docs master
* eProsima/Fast-DDS#4723
> [20893] Prepare 3.0.x-devel to become master

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.10.4.rst
- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This adds the notes from release v2.10.4
@Mergifyio backport 2.14.x 2.13.x
> [20995] Add notes from v2.10.4

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.6.9.rst
- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This PR adds the previous notes from `v2.6.9` and also marks the `2.6.x` branches as `maintenance`
@Mergifyio backport 2.14.x 2.13.x 2.10.x
> [21244] Include v2.6.9 release notes and `2.6.x` maintenance flag

- README.md
- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/discovery/static.rst
- docs/fastdds/dynamic_types/examples.rst
- docs/fastdds/getting_started/simple_app/includes/publisher.rst
- docs/fastdds/getting_started/simple_app/includes/subscriber.rst
- docs/fastdds/getting_started/simple_app/includes/sum_and_next_steps.rst
- docs/fastdds/getting_started/simple_python_app/includes/publisher.rst
- docs/fastdds/getting_started/simple_python_app/includes/subscriber.rst
- docs/fastdds/getting_started/simple_python_app/includes/sum_and_next_steps.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/fastdds/security/access_control_plugin/access_control_plugin.rst
- docs/fastdds/transport/shared_memory/shared_memory.rst
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/use_cases/request_reply/request_reply.rst
- docs/fastdds/use_cases/statistics_module/statistics_module.rst
- docs/fastdds/use_cases/well_known_deployments/well_known_deployments.rst
- docs/fastdds/use_cases/zero_copy/zero_copy.rst
- docs/fastdds/xml_configuration/making_xml_profiles.rst
- docs/fastddsgen/pubsub_app/includes/sum_and_next_steps.rst
- docs/fastddsgen/usage/usage.rst
- docs/installation/configuration/cmake_options.rst
- docs/installation/sources/sources_linux.rst
- docs/installation/sources/sources_mac.rst
- docs/installation/sources/sources_windows.rst
In Docs stable version (latest tag v2.14.2 - 2.14.x - 2.x versions), there were broken links.
This PR move those to `2.x` reference so they are not broken anymore.
> [21320] Fix master references in stable version

- code/CodeTester.cpp
- code/DDSCodeTester.cpp
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
- code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.hpp
This PR update the source code to new changes introduced in:
- eprosima/fast-dds-gen#375
- eprosima/fast-dds#5066
> [21378] Refactor `TopicDataType`

- docs/fastdds/use_cases/large_data/large_data.rst
During the revision we missed this malformed snippet. This PR fixes the doc generation to display the complete snippet.
([See here](https://eprosima-fast-rtps--794.org.readthedocs.build/en/794/fastdds/use_cases/large_data/large_data.html#example-configuration))
> [21136] Fix Large data usecase flowcontrollers XML snippet

- docs/fastdds/library_overview/includes/architecture.rst
Misspell DataReaderHistory Update architecture.rst
Misspell DataReaderHistory Update architecture.rst
> Misspell DataReaderHistory Update architecture.rst

- .github/workflows/reusable-ubuntu-ci.yml
This PR makes Uubntu CI to update the apt sources list before actually installing the required ones. This solves [this error](https://github.com/eProsima/Fast-DDS-docs/actions/runs/10241035577)
@Mergifyio backport 2.14.x 2.10.x 2.6.x
- _N/A_ Documentation tests pass locally.
> [21366] Update apt dependencies in ubuntu github ci

- README.md
- code/Examples/C++/DDSHelloWorld/src/HelloWorldCdrAux.ipp
- docs/02-formalia/titlepage.rst
- docs/conf.py
- docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/ParticipantDiscoveryStatus.rst
- docs/fastdds/faq/dds_layer/dds_layer.rst
- docs/fastdds/faq/discovery/discovery.rst
- docs/fastdds/faq/environment_variables/environment_variables.rst
- docs/fastdds/faq/faq.rst
- docs/fastdds/faq/getting_started/getting_started.rst
- docs/fastdds/faq/logging/logging.rst
- docs/fastdds/faq/persistence_service/persistence_service.rst
- docs/fastdds/faq/rtps_layer/rtps_layer.rst
- docs/fastdds/faq/security/security.rst
- docs/fastdds/faq/statistics_module/statistics_module.rst
- docs/fastdds/faq/transport_layer/transport_layer.rst
- docs/fastdds/faq/xml_profiles/xml_profiles.rst
- docs/fastdds/faq/xtypes/xtypes.rst
- docs/fastdds/statistics/monitor_service/intro.rst
- docs/index.rst
- docs/requirements.txt
- docs/spelling_wordlist.txt
Pull request was opened from a forked repository, so CI could not run. Feature merged in an intermediate branch to force CI.
> [21416] Add FAQs section (#883)

- docs/fastdds/discovery/discovery_server.rst
- docs/fastdds/getting_started/simple_app/includes/sum_and_next_steps.rst
- docs/fastdds/rtps_layer/rtps_layer.rst
- docs/fastdds/transport/shared_memory/shared_memory.rst
- docs/fastdds/transport/tcp/tcp.rst
- docs/fastdds/use_cases/request_reply/request_reply.rst
- docs/fastdds/use_cases/well_known_deployments/well_known_deployments.rst
- docs/fastdds/use_cases/zero_copy/zero_copy.rst
This PR updates the Fast DDS example links in the documentation to the new urls
Note: spelling issue (unknown word `reachability`) is fixed in the [bump PR](https://github.com/eProsima/Fast-DDS-docs/pull/884/files#diff-94d41e6faf6c8f9c8faefc24c63640d92a798138e3eb709d528c4159e5b33d64)
> [21482] Fix example links

- docs/fastdds/discovery/includes/disc_phases.rst
fix a syntax error for fastdds discovery phase docs
> fix(fastdds):fix fastdds discovery docs error

- docs/notes/previous_versions/v3.0.1.rst
This PR updates Fast DDS v3.0.1 release notes  with the latest PR merged
> [21663] Update release notes with latest PR merged

- docs/index.rst
- docs/installation/configuration/cmake_options.rst
- docs/notes/migration_guide.rst
- docs/spelling_wordlist.txt
Documentation related to PR: https://github.com/eProsima/Fast-DDS/pull/5281
- N/A: Code snippets related to the added documentation have been provided.
- N/A: Applicable backports have been included in the description.
> [21797] Add Fast DDS v3 Migration Guide

- docs/notes/migration_guide.rst
- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v3.0.1.rst
- docs/notes/previous_versions/v3.1.0.rst
- docs/notes/versions.rst
> [21783] Add notes for Fast DDS `v3.1.0`

- docs/02-formalia/titlepage.rst
This PR updates the commercial support section and fixes a bullet point list
> [21873] Update commercial support section

- README.md
- docs/02-formalia/titlepage.rst
This PR updates the Fast DDS docs README's commercial support section
@Mergifyio backport 3.0.x 2.14.x 2.10.x 2.6.x 
- **N/A** CI passes without warnings or errors.
> [21890] Update commercial support section in project README

- docs/fastdds/getting_started/simple_python_app/includes/prerequisites.rst
- docs/fastdds/getting_started/simple_python_app/simple_python_app.rst
This PR includes a link to the python installation section (linux from sources) in the python getting started section.
@Mergifyio backport 3.0.x 2.14.x 2.10.x 2.6.x
- **N//A** Code snippets related to the added documentation have been provided.
> [21907] Include link to Python installation Getting started

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.10.6.rst
- docs/notes/versions.rst
This adds the notes from release v2.10.6
@Mergifyio backport 3.1.x 3.0.x 2.14.x
> [21755] Add notes from v2.10.6

- docs/docker/fastdds/fast_dds.rst
- docs/docker/fastdds_suite/fast_dds_suite.rst
- docs/installation/sources/sources_qnx.rst
I updated the command to execute "hello_world" and "configuration examples use the new version.
> [21891] Correct examples commands

- docs/fastdds/getting_started/simple_app/includes/publisher.rst
- docs/fastdds/library_overview/includes/architecture.rst
Fix some typos found while reviewing Fast-DDS documentation.
> Fix some typos

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.4.rst
- docs/notes/versions.rst
This adds the notes from release `v2.14.4`.
@Mergifyio backport 3.1.x 3.0.x 
> [21560] Add v2.14.4 release notes

- docs/notes/notes.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v3.1.0.rst
- docs/notes/previous_versions/v3.1.1.rst
- docs/notes/versions.rst
This brings the release notes from v3.1.1 into master
> [21832] Add release notes from `v3.1.1`

- docs/notes/previous_versions/previous_versions.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v3.0.2.rst
- docs/notes/versions.rst
This adds the notes from release v3.0.2
@Mergifyio backport 3.1.x
- __N/A__ Code snippets related to the added documentation have been provided.
- __N/A__ Documentation tests pass locally.
- __N/A__ Applicable backports have been included in the description.
- __N/A__ CI passes without warnings or errors.
> [21627] Add notes from v3.0.2

- docs/notes/previous_versions/v3.0.2.rst
This PR correct a error on the release notes for fastdds 3.0.2.
- __N/A__ Code snippets related to the added documentation have been provided.
- __N/A__ Documentation tests pass locally.
- __N/A__ Applicable backports have been included in the description.
> [21627] Correction of release notes for 3.0.2

- code/Examples/Python/HelloWorld/HelloWorldPublisher.py
- code/Examples/Python/HelloWorld/HelloWorldSubscriber.py
This PR updates the `setName` `getName` to snake case in `Fast DDS Python` publisher and subscriber example. 
> [22322] Update Fast DDS Python Publisher and Subscriber example script

- code/DDSCodeTester.cpp
- docs/03-exports/aliases-api.include
- docs/fastdds/xtypes/idl_parsing.rst
- docs/fastdds/xtypes/language_binding.rst
- docs/fastdds/xtypes/xtypes.rst
This PR documents the feature introduced in this [PR](https://github.com/eProsima/Fast-DDS/pull/4943).
> XTYPES IDL parsing feature

- .github/workflows/weekly-ubuntu-ci.yml
Ubuntu 20.04 is EOL since 15/04/2025
> [21559] Upgrade weekly 2.6.x ci to Ubuntu-22.04

- docs/fastdds/use_cases/zero_copy/zero_copy.rst
This PR adds the extensibility(FINAL) to the idl of the "Getting started" section of Zero-Copy communication
@Mergifyio backport 3.1.x 
> [23071] Add extensibility in zero-copy idl example

- code/FastDDSGenCodeTester.cpp
- docs/fastddsgen/dataTypes/dataTypes.rst
This PR updates Fast DDS documentation to exemplify how custom templates can be applied to included IDL files.
- https://github.com/eProsima/Fast-DDS-Gen/pull/472
> [23150] Docs - Apply custom templates to included IDL files

- docs/notes/previous_versions/previous_versions.rst
- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.10.0.rst
- docs/notes/previous_versions/v2.10.1.rst
- docs/notes/previous_versions/v2.10.2.rst
- docs/notes/previous_versions/v2.10.3.rst
- docs/notes/previous_versions/v2.10.4.rst
- docs/notes/previous_versions/v2.10.5.rst
- docs/notes/previous_versions/v2.10.6.rst
- docs/notes/previous_versions/v2.10.7.rst
- docs/notes/versions.rst
After releasing [v2.10.7](https://github.com/eProsima/Fast-DDS/releases/tag/v2.10.7), which marks the EOL of 2.10.x, this PR adds its release notes and moves all 2.10.x versions to the previously supported versions section.
@Mergifyio backport 2.14.x
> [22188] Add notes from 2.10.7 and move 2.10.x to EOL versions

- .github/workflows/nightly-ubuntu-ci.yml
[Branchout 3.3.x](https://github.com/eProsima/Fast-DDS-docs/pull/1079) had missing quotes in the nightly for `3.2.x` 
> Hotfix `3.2.x` nightly workflow file

- docs/notes/versions.rst
This PR updates Fast DDS Gen compatibility version on Fast DDS 3.2.x
@Mergifyio backport 3.3.x 3.2.x
> [23657] Update Fast DDS Gen compatibility version on Fast DDS 3.2.x

- docs/notes/previous_versions/supported_versions.rst
- docs/notes/previous_versions/v2.14.5.rst
- docs/notes/versions.rst
This PR includes the release notes from `v2.14.5` into master and supported branches
@Mergifyio backport 3.3.x 3.2.x
> [22417] Add 2.14.5 release notes

- docs/notes/versions.rst
Updating Fast CDR tags after its [v2.3.1 release](https://github.com/eProsima/Fast-CDR/releases/tag/v2.3.1)
@Mergifyio backport 3.3.x 3.2.x
> [23520] Update fastcdr release in Library dependencies section

- docs/02-formalia/titlepage.rst
@Mergifyio backport 3.3.x 3.2.x 2.14.x
> New commercial message.

- docs/02-formalia/titlepage.rst
> New url for commercial message

- docs/02-formalia/titlepage.rst
- docs/conf.py
This PR add a note introducing Fast DDS Pro and extends the `Pro` badge with a tooltip.
> Fast DDS Pro note and badge tooltip

- docs/notes/versions.rst
- docs/spelling_wordlist.txt
This updates the dependencies and compatibilities section in preparation for the next release.
It also fixes some versions on 3.2.x and 3.3.x
- _N/A_: The ``Pro`` version badge has been added if the documented feature is exclusive to Fast DDS Pro.
> [23520] Update dependencies and compatibilities for 3.4.0
